
BattleGroundEnemiesDB = {
["profileKeys"] = {
["Cocoonjkdead - Aerie Peak"] = "Default",
["Justinjames - Sentinels"] = "Default",
["Mstcll - Borean Tundra"] = "Default",
["Mstcll - Garrosh"] = "Default",
["Yungmyst - Area 52"] = "Default",
["Réðçräñé - Sargeras"] = "Default",
["Representing - Area 52"] = "Default",
["Badplat - Sargeras"] = "Default",
["Lotusflowers - Sargeras"] = "Default",
["Nerfmw - Moon Guard"] = "Default",
["Vivifying - Sentinels"] = "Default",
["Mysticallx - Tichondrius"] = "Default",
["Flowerlotus - Sentinels"] = "Default",
["Mw - Tichondrius"] = "Default",
["Cocoonjkdead - Sentinels"] = "Default",
["Vezimmarr - Aerie Peak"] = "Default",
["Mysticall - Bleeding Hollow"] = "Default",
["Harambad - Sargeras"] = "Default",
["Onlyplaydh - Sargeras"] = "Default",
["Gréëñðrägoñ - Sargeras"] = "Default",
["Trialfornowa - Cenarius"] = "Default",
["Yungmyst - Sentinels"] = "Default",
["Gréëñðrägøñ - Sargeras"] = "Default",
["Mysticbankk - Area 52"] = "Default",
["Hystoricall - Sentinels"] = "Default",
["Enveloping - Area 52"] = "Default",
["Mysticall - Tichondrius"] = "Default",
["Mysticallxd - Sargeras"] = "Default",
["Darkapostle - Tichondrius"] = "Default",
["Coocoocachu - Sargeras"] = "Default",
["Zft - Sentinels"] = "Default",
["Buffmwpls - Sargeras"] = "Default",
["Onlyplaymonk - Sargeras"] = "Default",
["Yungmyst - Sargeras"] = "Default",
["Cocoonjkdead - Bleeding Hollow"] = "Default",
["Mysticallx - Area 52"] = "Mysticall",
["Cocoonjkdead - Area 52"] = "Default",
["Mwreroll - Sargeras"] = "Default",
["Soullkeeper - Sargeras"] = "Default",
["Nightbllade - Area 52"] = "Default",
["Mysticall - Moon Guard"] = "Default",
["Soullstëaler - Sentinels"] = "Default",
["Mysticbankk - Sargeras"] = "Default",
["Moosticall - Sentinels"] = "Default",
["Weavethemist - Azjol-Nerub"] = "Default",
["Mysticbankk - Sentinels"] = "Default",
["Onlyplaymage - Sargeras"] = "Default",
["Iamdeadinsid - Sentinels"] = "Default",
["Réðçräñé - Sentinels"] = "Default",
["Healjkoom - Sargeras"] = "Default",
["Mstcll - Aerie Peak"] = "Default",
["Sevenseconds - Area 52"] = "Default",
["Representing - Sargeras"] = "Default",
["Coccoon - Area 52"] = "Default",
["Vivifying - Area 52"] = "Default",
["Bovadeez - Bleeding Hollow"] = "Default",
["Thunderbadx - Sargeras"] = "Default",
["Mstcll - Sentinels"] = "Default",
["Onlyplaydru - Sargeras"] = "Default",
["Onlyplaymonk - Area 52"] = "Default",
["Weavethemist - Sargeras"] = "Default",
["Stylle - Sentinels"] = "Default",
["Mstcll - Sargeras"] = "Default",
["Mstcll - Blackwater Raiders"] = "Default",
["Mysticallx - Sargeras"] = "Default",
["Cincinatizoo - Sargeras"] = "Default",
["Mysticbollt - Garrosh"] = "Default",
["Hydraxises - Lightning's Blade"] = "Default",
["Mstcll - Area 52"] = "Default",
["Mysticallxy - Area 52"] = "Default",
["Lifedestroys - Tichondrius"] = "Default",
["Nightmares - Sentinels"] = "Default",
["Mstcll - Echo Isles"] = "Default",
["Rsk - Sentinels"] = "Default",
["Mysticallx - Emerald Dream"] = "Default",
["Representing - Blackhand"] = "Default",
["Thunderbad - Sentinels"] = "Default",
["Mediumvibes - Sentinels"] = "Default",
["Onlyplaysub - Sargeras"] = "Default",
["Onlyplayfury - Sargeras"] = "Default",
["Soullstëaler - Blackhand"] = "Default",
["Mysticbankk - Tichondrius"] = "Default",
["Kickthesun - Sargeras"] = "Default",
["Sevenseconds - Sargeras"] = "Default",
["Misstickle - Sargeras"] = "Default",
["Mysticall - Sentinels"] = "Default",
["Nerfmw - Sargeras"] = "Default",
["Chithion - Zul'jin"] = "Default",
["Enveloping - Sentinels"] = "Default",
},
["profiles"] = {
["Default"] = {
["onlyShowWhenNewVersion"] = true,
["Allies"] = {
["Enabled"] = false,
["RangeIndicator_Frames"] = {
["Spec"] = true,
["Trinket"] = true,
["Power"] = false,
},
["15"] = {
["Enabled"] = false,
["Position_Y"] = 376.8889848205799,
["Position_X"] = 849.7783191879716,
},
["5"] = {
["Enabled"] = false,
},
},
["Font"] = "2002 Bold",
["lastReadVersion"] = "9.2.0.11",
["Enemies"] = {
["40"] = {
["Enabled"] = false,
["Position_Y"] = 679.8223254892582,
["Position_X"] = 1026.133444986081,
},
["RangeIndicator_Frames"] = {
["Spec"] = true,
},
["ShowRealmnames"] = false,
["15"] = {
["DrTracking_Container_RelativePoint"] = "RIGHT",
["Trinket_RelativePoint"] = "LEFT",
["BarVerticalSpacing"] = 0,
["RoleIcon_Enabled"] = false,
["Auras_Enabled"] = false,
["Spec_Width"] = 26,
["Racial_Enabled"] = false,
["HealthBar_Texture"] = "Blizzard",
["Trinket_OffsetX"] = -20,
["Name_Fontsize"] = 16,
["Trinket_Cooldown_EnableTextshadow"] = true,
["PowerBar_Enabled"] = true,
["BarWidth"] = 234,
["Framescale"] = 1.3,
["Trinket_Width"] = 21,
["Position_Y"] = 439.3961689936077,
["Auras_Debuffs_Enabled"] = false,
["Position_X"] = 923.8360153771355,
},
["5"] = {
["Enabled"] = false,
["Position_Y"] = 360.533450570374,
["Position_X"] = 1047.467212863776,
},
["RangeIndicator_Alpha"] = 0.75,
},
},
["Mysticall"] = {
["Font"] = "2002 Bold",
["Enemies"] = {
["15"] = {
["DrTracking_Container_RelativePoint"] = "RIGHT",
["Trinket_RelativePoint"] = "LEFT",
["BarVerticalSpacing"] = 0,
["RoleIcon_Enabled"] = false,
["Auras_Enabled"] = false,
["Spec_Width"] = 23,
["Racial_Enabled"] = false,
["HealthBar_Texture"] = "Blizzard",
["Auras_Debuffs_Enabled"] = false,
["Trinket_Cooldown_EnableTextshadow"] = true,
["PowerBar_Enabled"] = true,
["Framescale"] = 1.3,
["Trinket_Width"] = 21,
["BarWidth"] = 234,
["Trinket_OffsetX"] = -20,
["Position_Y"] = 474.2406732781674,
["Name_Fontsize"] = 16,
["Position_X"] = 920.1045021659666,
},
["40"] = {
["Enabled"] = false,
["Position_Y"] = 679.8223254892582,
["Position_X"] = 1026.133444986081,
},
["RangeIndicator_Frames"] = {
["Spec"] = true,
},
["5"] = {
["Enabled"] = false,
["Position_Y"] = 132.9776073866378,
["Position_X"] = 1208.88900496695,
},
["RangeIndicator_Alpha"] = 0.75,
["ShowRealmnames"] = false,
},
["onlyShowWhenNewVersion"] = true,
["lastReadVersion"] = "9.2.0.9",
["DisableArenaFrames"] = true,
["Allies"] = {
["Enabled"] = false,
["15"] = {
["Position_Y"] = 404.6222754226801,
["Position_X"] = 845.5115656124326,
},
["RangeIndicator_Frames"] = {
["Trinket"] = true,
["Spec"] = true,
["DRContainer"] = true,
["Power"] = false,
},
},
},
},
}
