
BattleGroundEnemiesDB = {
["profileKeys"] = {
["Cocoonjkdead - Aerie Peak"] = "Default",
["Justinjames - Sentinels"] = "Default",
["Mstcll - Borean Tundra"] = "Default",
["Mstcll - Garrosh"] = "Default",
["Yungmyst - Area 52"] = "Default",
["Lotusflower - Dalvengyr"] = "Default",
["Réðçräñé - Sargeras"] = "Mysticall",
["Representing - Area 52"] = "Default",
["Badplat - Sargeras"] = "Default",
["Lotusflowers - Sargeras"] = "Default",
["Nerfmw - Moon Guard"] = "Default",
["Vivifying - Sentinels"] = "Default",
["Mysticallx - Tichondrius"] = "Default",
["Flowerlotus - Sentinels"] = "Default",
["Mw - Tichondrius"] = "Default",
["Cocoonjkdead - Sentinels"] = "Default",
["Vezimmarr - Aerie Peak"] = "Default",
["Mysticall - Bleeding Hollow"] = "Default",
["Harambad - Sargeras"] = "Default",
["Onlyplaydh - Sargeras"] = "Default",
["Gréëñðrägoñ - Sargeras"] = "Default",
["Trialfornowa - Cenarius"] = "Default",
["Yungmyst - Sentinels"] = "Default",
["Gréëñðrägøñ - Sargeras"] = "Default",
["Mysticbankk - Area 52"] = "Default",
["Hystoricall - Sentinels"] = "Default",
["Enveloping - Area 52"] = "Default",
["Mysticall - Tichondrius"] = "Default",
["Mysticallxd - Sargeras"] = "Default",
["Darkapostle - Tichondrius"] = "Default",
["Coocoocachu - Sargeras"] = "Default",
["Cocoonjkdead - Area 52"] = "Default",
["Magycall - Emerald Dream"] = "Default",
["Chithion - Zul'jin"] = "Default",
["Nightbllade - Area 52"] = "Default",
["Onlyplaymw - Durotan"] = "Default",
["Mwreroll - Sargeras"] = "Default",
["Zft - Sentinels"] = "Default",
["Nerfmw - Sargeras"] = "Default",
["Weavethemist - Azjol-Nerub"] = "Default",
["Buffmwpls - Sargeras"] = "Default",
["Baotu - Sargeras"] = "Default",
["Onlyplaymonk - Sargeras"] = "Default",
["Onlyplaymage - Sargeras"] = "Default",
["Yungmyst - Sargeras"] = "Default",
["Cocoonjkdead - Bleeding Hollow"] = "Default",
["Réðçräñé - Sentinels"] = "Default",
["Kickthesun - Sargeras"] = "Default",
["Mysticallx - Area 52"] = "Mysticall",
["Onlyplayfury - Sargeras"] = "Default",
["Mstcll - Sargeras"] = "Default",
["Mysticallx - Sargeras"] = "Default",
["Hydraxises - Lightning's Blade"] = "Default",
["Mw - Sargeras"] = "Default",
["Mw - Turalyon"] = "Default",
["Tealcrayon - Anetheron"] = "Default",
["Mysticbankk - Sargeras"] = "Default",
["Moosticall - Sentinels"] = "Default",
["Mstcll - Echo Isles"] = "Default",
["Mysticbankk - Sentinels"] = "Default",
["Healjkoom - Sargeras"] = "Default",
["Iamdeadinsid - Sentinels"] = "Default",
["Curtimer - Emerald Dream"] = "Default",
["Green - Eitrigg"] = "Default",
["Mstcll - Aerie Peak"] = "Default",
["Sevenseconds - Area 52"] = "Default",
["Elamatrenn - Emerald Dream"] = "Default",
["Coccoon - Area 52"] = "Default",
["Stylle - Sentinels"] = "Default",
["Bovadeez - Bleeding Hollow"] = "Default",
["Thunderbadx - Sargeras"] = "Default",
["Mstcll - Sentinels"] = "Default",
["Onlyplaydru - Sargeras"] = "Default",
["Cincinatizoo - Sargeras"] = "Default",
["Craaruun - Eitrigg"] = "Default",
["Weavethemist - Sargeras"] = "Default",
["Onlyplaymonk - Area 52"] = "Default",
["Mstcll - Blackwater Raiders"] = "Default",
["Vivifying - Area 52"] = "Default",
["Nightmares - Sentinels"] = "Default",
["Mysticbollt - Garrosh"] = "Default",
["Mediumvibes - Sentinels"] = "Default",
["Mstcll - Area 52"] = "Default",
["Mysticallxy - Area 52"] = "Default",
["Lifedestroys - Tichondrius"] = "Default",
["Mysticbankk - Tichondrius"] = "Default",
["Soullstëaler - Sentinels"] = "Default",
["Rsk - Sentinels"] = "Default",
["Mysticallx - Emerald Dream"] = "Default",
["Representing - Blackhand"] = "Default",
["Thunderbad - Sentinels"] = "Default",
["Rsk - Shandris"] = "Default",
["Onlyplaysub - Sargeras"] = "Default",
["Representing - Sargeras"] = "Default",
["Soullstëaler - Blackhand"] = "Default",
["Mysticall - Moon Guard"] = "Default",
["Soullkeeper - Sargeras"] = "Default",
["Ggs - Detheroc"] = "Default",
["Misstickle - Sargeras"] = "Default",
["Mysticall - Sentinels"] = "Default",
["Sevenseconds - Sargeras"] = "Default",
["Jje - Vek'nilash"] = "Default",
["Enveloping - Sentinels"] = "Default",
},
["profiles"] = {
["Mysticall"] = {
["ShowBGEInArena"] = false,
["Enemies"] = {
["playerCountConfigs"] = {
nil,
{
["Position_X"] = 947.4663850724755,
["Position_Y"] = 348.2667890906305,
},
},
},
["onlyShowWhenNewVersion"] = true,
["lastReadVersion"] = "11.0.5.9",
["dbVersion"] = 2,
["Allies"] = {
["Enabled"] = false,
},
},
["Default"] = {
["ShowBGEInArena"] = false,
["onlyShowWhenNewVersion"] = true,
["Allies"] = {
["Enabled"] = false,
},
["DisableArenaFramesInArena"] = true,
["lastReadVersion"] = "11.0.5.9",
["Enemies"] = {
["playerCountConfigs"] = {
{
["Position_Y"] = 487.99998909235,
["Position_X"] = 856.2670121109404,
},
{
["PlayerCount"] = {
["Enabled"] = false,
},
["Framescale"] = 1.25,
["ButtonModules"] = {
["Racial"] = {
["Enabled"] = false,
["Height"] = false,
},
["SpecClassPriorityOne"] = {
["Height"] = false,
},
["Power"] = {
["Enabled"] = false,
},
["DRTracking"] = {
["Points"] = {
{
["OffsetY"] = 0,
},
},
},
["Trinket"] = {
["Height"] = false,
},
},
["Position_Y"] = 394.1336679140513,
["Position_X"] = 861.0673314888845,
},
{
["Enabled"] = false,
},
},
},
["dbVersion"] = 2,
["DisableRaidFramesInArena"] = true,
},
["Sargeras"] = {
["dbVersion"] = 2,
},
["MONK"] = {
["dbVersion"] = 2,
},
},
}
