
BetterBlizzPlatesDB = {
["npBgColorRGB"] = {
1,
1,
1,
1,
},
["classIndicatorFriendlyScale"] = 1.62,
["otherNpdeBuffFilterCC"] = false,
["doNotHideFriendlyHealthbarInPve"] = false,
["hideNPCArenaOnly"] = false,
["nameplateKeyAuraScale"] = 1,
["NamePlateClassificationScale"] = "1.25",
["hideNPCHideSecondaryPets"] = true,
["nameplateSelfWidth"] = 154.0000305175781,
["auraColor"] = false,
["nameplatePlayerLargerScale"] = "1.8",
["friendlyNpBuffFilterLessMinite"] = false,
["otherNpdeBuffFilterWatchList"] = true,
["castBarInterruptHighlighterColorDontInterrupt"] = false,
["enableNameplateAuraCustomisation"] = true,
["customTextureFriendly"] = "Dragonflight (BBP)",
["healthNumbersXPosXPos"] = 0,
["partyPointer"] = true,
["hideCastbarWhitelist"] = {
},
["colorNPCName"] = false,
["questIndicatorTestMode"] = false,
["targetIndicatorYPos"] = 0,
["executeIndicatorScale"] = 1,
["healerIndicatorRedCrossEnemy"] = true,
["focusTargetIndicatorTexture"] = "Shattered DF (BBP)",
["defaultFadeOutNPCsList"] = {
{
["id"] = 26125,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "DK pet",
["comment"] = "",
},
{
["id"] = 163366,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Magus(Army of the Dead)",
["comment"] = "",
},
{
["id"] = 24207,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Army of the Dead",
["comment"] = "",
},
{
["id"] = 29264,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Spirit Wolves (Enha Shaman)",
["comment"] = "",
},
{
["id"] = 95072,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Earth Elemental (Shaman)",
["comment"] = "",
},
{
["id"] = 31216,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Mirror Images (Mage)",
["comment"] = "",
},
{
["id"] = 62005,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Beast (Hunter)",
["comment"] = "",
},
{
["id"] = 105419,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Dire Basilisk (Hunter)",
["comment"] = "",
},
{
["id"] = 192337,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Void Tendril (Spriest)",
["comment"] = "",
},
{
["id"] = 136398,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Illidari Satyr",
["comment"] = "",
},
{
["id"] = 136408,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Darkhound",
["comment"] = "",
},
{
["id"] = 136403,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Void Terror",
["comment"] = "",
},
{
["id"] = 54983,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Treant",
["comment"] = "",
},
},
["friendlyClassColorName"] = true,
["castbarAlwaysOnTop"] = false,
["enemyNeutralHealthBarColorRGB"] = {
1,
1,
0,
},
["targetIndicatorScale"] = 1,
["changeNameplateBorderColor"] = false,
["disableCompactedAurasOnSelf"] = false,
["old_defaultLargeFontSize"] = 12,
["questIndicatorAnchor"] = "LEFT",
["otherNpBuffFilterPurgeable"] = false,
["otherNpdeBuffEnable"] = true,
["scStart"] = true,
["healthNumbersFriendly"] = false,
["combatIndicatorXPos"] = 0,
["friendlyNpdeBuffFilterWatchList"] = true,
["auraWhitelistColorsUpdated"] = true,
["hideCastbarList"] = {
},
["nameplateAurasEnemyCenteredAnchor"] = true,
["classIndicatorScale"] = 1.18,
["hpHeightSelfMana"] = 10.8,
["showNpcTitle"] = false,
["partyPointerCCAuras"] = true,
["arenaIdAnchor"] = "TOP",
["importantCCDisarm"] = true,
["hideNameplateAuraTooltip"] = false,
["nameplateAurasPersonalYPos"] = 0,
["castBarNoninterruptibleColor"] = {
0.4,
0.4,
0.4,
},
["npAuraDiseaseRGB"] = {
1,
0.53,
0.14,
},
["healthNumbersUseMillions"] = false,
["focusTargetIndicatorTestMode"] = false,
["disableCVarForceOnLogin"] = false,
["old_defaultFontSize"] = 9,
["partyIndicatorModeThree"] = false,
["importantBuffsDefensives"] = true,
["customHpHeight"] = 0,
["arenaIndicatorModeOff"] = false,
["nameplateAuraRightToLeft"] = false,
["enemyColorThreatCombatOnly"] = false,
["nameplateShowEnemyGuardians"] = "1",
["castBarEmphasisSparkHeight"] = 35,
["castBarPixelBorder"] = false,
["nameplateEnemyHeight"] = 64.125,
["targetIndicatorChangeTexture"] = false,
["nameplateAurasYPos"] = 0,
["castBarEmphasisColor"] = false,
["petIndicatorHideSecondaryPets"] = true,
["nameplateShowFriendlyTotems"] = "1",
["enableMidnightNameplateTweaks"] = true,
["nameplateAurasNoNameYPos"] = 0,
["classIconReactionBorder"] = false,
["questIndicatorYPos"] = 0,
["bgIndicatorShowOrbs"] = true,
["enemyHealthBarColor"] = false,
["nameplateShowFriendlyMinions"] = "0",
["arenaIdXPos"] = 0,
["friendlyNameplatesOnlyInBgs"] = true,
["arenaIndicatorModeThree"] = false,
["hideNPCsWhitelist"] = {
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 61245,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Capacitor Totem",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 105451,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Counterstrike Totem",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 100943,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Earthen Wall Totem",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 60561,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Earthgrab Totem",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 179193,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Fel Obelisk (Warlock)",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 17252,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Felguard (Demo Pet)",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 417,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Felhunter (Warlock)",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 5925,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Grounding Totem",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 114565,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Guardian Queen (prot pala)",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 59764,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Healing Tide Totem",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 165189,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Hunter pet (they all have same ID)",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 69792,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Monk Image (Green)",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 69791,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Monk Image (Red)",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 107100,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Observer (Warlock)",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 185800,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Past Self (Evoker)",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 101398,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Psyfiend (Spriest)",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 225672,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Shadow (Priest Re-Fear)",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 19668,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Shadowfiend",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 53006,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Spirit Link Totem",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 59712,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Stone Bulwark Totem",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 1863,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Succubus (Warlock)",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 225409,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Surging Totem",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 5913,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Tremor Totem",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 135002,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Tyrant (Warlock)",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 224466,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Voidwrath (Priest)",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 119052,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "War Banner",
},
},
["castBarTextScale"] = 0.65,
["otherNpdeBuffFilterAll"] = false,
["colorNPC"] = false,
["classIndicatorAnchor"] = "TOP",
["partyPointerYPosYPos"] = -40,
["healthNumbersXPos"] = 0,
["arenaSpecAnchor"] = "TOP",
["questIndicator"] = false,
["nameplateFriendlyHeight"] = 1,
["partySpecScale"] = 1.4,
["nameplateMinScale"] = 1.25,
["otherNpBuffEmphasisedBorder"] = false,
["personalNpBuffFilterImportantBuffs"] = false,
["raidmarkIndicatorAnchor"] = "TOP",
["nameplateShowFriendlyGuardians"] = "0",
["totemIndicatorHideNameAndShiftIconDown"] = false,
["nameplateAuraKeyAuraPositionFriendly"] = false,
["nameplateAuraRowAmount"] = 5,
["dpsOrHealNoAggroColorRGB"] = {
0,
1,
0,
1,
},
["defaultLargeNamePlateFontFlags"] = "",
["castBarInterruptHighlighterEndTime"] = 0.6,
["nameplateAuraRelativeAnchor"] = "TOPLEFT",
["castBarInterruptHighlighterEndPercentage"] = 85,
["partyPointerArenaOnly"] = false,
["ccIconAnchor"] = "TOP",
["healerIndicatorYPos"] = 0,
["ccIconYPosYPos"] = 29,
["npBorderNpcColorRGB"] = {
0,
0,
0,
1,
},
["partyPointerHideAll"] = false,
["customHpFriendlyHeight"] = 0,
["hideEnemyNameText"] = true,
["darkModeNameplateColor"] = 0.2,
["npBorderEnemyColorRGB"] = {
1,
0,
0,
1,
},
["hideRaidmarkIndicator"] = false,
["nameplateMaxAlpha"] = 1,
["changeHealthbarHeight"] = true,
["nameplateAuraEnlargedScale"] = 1,
["otherNpdeBuffFilterLessMinite"] = false,
["healthNumbersNotOnFullHp"] = false,
["enableCustomFontOutline"] = false,
["castBarInterruptHighlighterInterruptRGB"] = {
0,
1,
0.8784314393997192,
1,
},
["auraBlacklist"] = {
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Corrupt the blood",
["comment"] = "",
},
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Crippling Poison",
["comment"] = "",
},
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Fatal Intent",
["comment"] = "",
},
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Find Weakness",
["comment"] = "",
},
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Infected Wounds",
["comment"] = "",
},
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Spoils of War",
["comment"] = "",
},
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Wound Poison",
["comment"] = "",
},
},
["partyPointerWidth"] = 36,
["nameplateResourceScale"] = 0.7,
["nameplateHorizontalScale"] = "1.4",
["healerIndicatorEnemyOnly"] = true,
["hideNpcMurlocScale"] = 1,
["old_defaultLargeNamePlateFontFlags"] = "",
["npBorderFriendFoeColor"] = false,
["healthNumbersFontOutline"] = "OUTLINE",
["hideNameplateAuras"] = false,
["hidePersonalBarManaFrame"] = false,
["arenaIndicatorBg"] = true,
["arenaSpecScale"] = 1.4,
["focusTargetIndicatorChangeTexture"] = false,
["classIndicatorHideRaidMarker"] = true,
["partyPointerXPos"] = 0,
["classIconArenaOnly"] = false,
["classIconAlwaysShowTank"] = true,
["castBarEmphasisText"] = false,
["nameplateFriendlyWidth"] = 60,
["classicNameplates"] = false,
["skipGUI"] = false,
["castBarInterruptHighlighterStartPercentage"] = 15,
["petIndicatorScale"] = 1,
["nameplateOccludedAlphaMultScale"] = 1,
["otherNpBuffFilterImportantBuffs"] = false,
["fakeNameRaiseStrata"] = true,
["executeIndicatorThreshold"] = 40,
["totemIndicatorScaleUpImportant"] = true,
["npBorderFriendlyColorRGB"] = {
0,
1,
0,
1,
},
["interruptedByIndicator"] = false,
["tankFullAggroColorRGB"] = {
0,
1,
0,
1,
},
["partyModeSettingKey"] = "Off",
["healerIndicatorScale"] = 1,
["castBarEmphasisOnlyInterruptable"] = false,
["totemListUpdateTWW6"] = true,
["nameplateShowFriendlyPlayerMinions"] = "0",
["nameplateAuraWidthGapScale"] = 1,
["arenaSpecXPos"] = 0,
["castEmphasisList"] = {
{
["name"] = "Cyclone",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
},
{
["name"] = "Fear",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
},
{
["name"] = "Haymaker",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
},
{
["name"] = "Hex",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
},
{
["name"] = "Lightning Lasso",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
},
{
["name"] = "Mass Polymorph",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
},
{
["name"] = "Polymorph",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
},
{
["name"] = "Repentance",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
},
{
["name"] = "Ring of Frost",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
},
{
["name"] = "Shadowfury",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
},
{
["name"] = "Sleep Walk",
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
},
},
["nameplateShowEnemyMinus"] = "0",
["shortArenaSpecName"] = true,
["classColorPersonalNameplate"] = true,
["darkModeNameplateResource"] = true,
["hideLevelFrame"] = true,
["fadeOutNPC"] = true,
["otherNpdeBuffFilterOnlyMe"] = true,
["enemyColorThreatCombatOnlyPlayer"] = false,
["smallPetsWidth"] = 20,
["importantCCSilence"] = true,
["auraColorList"] = {
},
["personalNpBuffFilterOnlyMe"] = false,
["separateAuraBuffRow"] = true,
["nameplateAuraHeightGapScale"] = 2,
["healthNumbersYPosYPos"] = 1,
["castBarEmphasisIcon"] = false,
["healerIndicatorAnchor"] = "TOPRIGHT",
["executeIndicatorShowDecimal"] = true,
["castBarEmphasisIconScale"] = 2,
["alwaysHideFriendlyCastbar"] = true,
["nameplateShowFriendlyNPCs"] = "0",
["healthNumbersShowDecimal"] = false,
["hideNPCsList"] = {
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Beast",
["comment"] = "",
},
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Hyena",
["comment"] = "",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 31216,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Mirror Images (Mage)",
},
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Raptor",
["comment"] = "",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 55659,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Wild Imp (Warlock)",
},
},
["partyIndicatorModeOne"] = false,
["adjustPersonalBarPosition"] = false,
["classIndicator"] = true,
["alwaysHideEnemyCastbar"] = false,
["castBarEmphasisHeightValue"] = 24,
["questIndicatorXPos"] = 0,
["otherNpdeBuffFilterBlacklist"] = true,
["castBarIconXPos"] = 5,
["nameplateOccludedAlphaMult"] = 1,
["fadeNPCPvPOnly"] = false,
["sortCompactedAurasFirst"] = false,
["totemIndicatorNpcList"] = {
[60561] = {
["important"] = false,
["name"] = "Earthgrab Totem",
["hideIcon"] = false,
["color"] = {
0.75,
0.31,
0.1,
},
["duration"] = 30,
["icon"] = 136100,
["size"] = 24,
},
[61245] = {
["important"] = true,
["name"] = "Capacitor Totem",
["hideIcon"] = false,
["color"] = {
1,
0.69,
0,
},
["duration"] = 2,
["icon"] = 136013,
["size"] = 24,
},
[5913] = {
["important"] = true,
["icon"] = 136108,
["name"] = "Tremor Totem",
["hideIcon"] = false,
["color"] = {
0.49,
0.9,
0.08,
},
["duration"] = 13,
["hideHp"] = true,
["size"] = 24,
},
[53006] = {
["important"] = true,
["name"] = "Spirit Link Totem",
["hideIcon"] = false,
["color"] = {
0,
1,
0.78,
},
["duration"] = 6,
["icon"] = 237586,
["size"] = 24,
},
[5925] = {
["important"] = true,
["name"] = "Grounding Totem",
["hideIcon"] = false,
["color"] = {
1,
0,
1,
},
["duration"] = 3,
["icon"] = 136039,
["size"] = 24,
},
[105427] = {
["important"] = false,
["name"] = "Totem of Wrath",
["hideIcon"] = false,
["color"] = {
1,
0.27,
0.59,
},
["duration"] = 15,
["icon"] = 135829,
["size"] = 24,
},
[225672] = {
["duration"] = 4,
["icon"] = 136184,
["name"] = "Shadow",
["hideIcon"] = false,
["color"] = {
0.49,
0,
1,
},
["important"] = false,
["hideHp"] = true,
["size"] = 20,
},
[194118] = {
["important"] = false,
["name"] = "Tranquil Air Totem",
["hideIcon"] = false,
["color"] = {
0,
1,
0.78,
},
["duration"] = 20,
["icon"] = 538575,
["size"] = 24,
},
[19668] = {
["duration"] = 15,
["name"] = "Shadowfiend",
["hideIcon"] = false,
["color"] = {
1,
0.69,
0,
},
["important"] = false,
["icon"] = 136199,
["size"] = 20,
},
[59764] = {
["important"] = true,
["name"] = "Healing Tide Totem",
["hideIcon"] = false,
["color"] = {
0,
1,
0.39,
},
["duration"] = 10,
["icon"] = 538569,
["size"] = 24,
},
[107024] = {
["important"] = true,
["name"] = "Fel Lord",
["hideIcon"] = false,
["color"] = {
1,
0.69,
0,
},
["duration"] = 15,
["icon"] = 1113433,
["size"] = 30,
},
[3527] = {
["important"] = false,
["name"] = "Healing Stream Totem",
["hideIcon"] = false,
["color"] = {
0,
1,
0.78,
},
["duration"] = 18,
["icon"] = 135127,
["size"] = 24,
},
[104818] = {
["important"] = true,
["name"] = "Ancestral Protection Totem",
["hideIcon"] = false,
["color"] = {
0,
1,
0.78,
},
["duration"] = 33,
["icon"] = 136080,
["size"] = 30,
},
[114565] = {
["important"] = true,
["name"] = "Guardian of the Forgotten Queen",
["hideIcon"] = false,
["color"] = {
1,
0,
1,
},
["duration"] = 10,
["icon"] = 135919,
["size"] = 24,
},
[105451] = {
["important"] = true,
["name"] = "Counterstrike Totem",
["hideIcon"] = false,
["color"] = {
1,
0.27,
0.59,
},
["duration"] = 15,
["icon"] = 511726,
["size"] = 24,
},
[14465] = {
["name"] = "Alliance Battle Standard",
["hideIcon"] = false,
["color"] = {
0,
0.22,
1,
},
["important"] = true,
["icon"] = 132486,
["size"] = 24,
},
[5923] = {
["important"] = false,
["name"] = "Poison Cleansing Totem",
["hideIcon"] = false,
["color"] = {
0.49,
0.9,
0.08,
},
["duration"] = 9,
["icon"] = 136070,
["size"] = 24,
},
[179867] = {
["important"] = false,
["name"] = "Static Field Totem",
["hideIcon"] = false,
["color"] = {
0,
1,
0.78,
},
["duration"] = 6,
["icon"] = 1020304,
["size"] = 24,
},
[101398] = {
["important"] = true,
["name"] = "Psyfiend",
["hideIcon"] = false,
["color"] = {
0.49,
0,
1,
},
["duration"] = 12,
["icon"] = 537021,
["size"] = 30,
},
[14466] = {
["name"] = "Horde Battle Standard",
["hideIcon"] = false,
["color"] = {
1,
0,
0,
},
["important"] = true,
["icon"] = 132485,
["size"] = 24,
},
[100943] = {
["important"] = true,
["name"] = "Earthen Wall Totem",
["hideIcon"] = false,
["color"] = {
0.78,
0.49,
0.35,
},
["duration"] = 18,
["icon"] = 136098,
["size"] = 30,
},
},
["classIconColorBorder"] = true,
["enemyNeutralColorNameRGB"] = {
1,
1,
0,
},
["targetIndicatorColorName"] = false,
["classIconHealthNumbers"] = false,
["partyPointerHealerOnly"] = false,
["nameplateAuraRowAbove"] = true,
["totemIndicatorWidthEnabled"] = false,
["nameplateEnemyWidth"] = 128,
["classIndicatorShowPet"] = true,
["nameplateAuraCompactedSquare"] = false,
["nameplateShowAll"] = "1",
["absorbIndicatorOnPlayersOnly"] = false,
["fadeAllButTarget"] = false,
["healthNumbersYPos"] = 1,
["raidmarkIndicatorXPos"] = 0,
["bgIndicator"] = true,
["targetNameplateAuraScaleEnabled"] = false,
["castBarDelayedInterruptColor"] = {
0,
1,
0.7843137979507446,
1,
},
["friendlyNpdeBuffFilterCC"] = true,
["otherNpBuffFilterLessMinite"] = false,
["hideResourceOnFriend"] = false,
["skipAdjustingFixedFonts"] = false,
["friendlyNameplatesOnlyInWorld"] = true,
["friendlyNpBuffFilterWatchList"] = false,
["showCastbarIfTarget"] = false,
["partyPointerAlwaysShowPet"] = false,
["sortEnlargedAurasFirst"] = true,
["castBarIconPosReset"] = true,
["classIndicatorFrameStrataHigh"] = false,
["absorbIndicatorXPos"] = 0,
["partyIndicatorModeFive"] = false,
["showGuildNames"] = false,
["friendlyNameplatesOnlyInEpicBgs"] = false,
["classIndicatorPinMode"] = false,
["targetIndicator"] = false,
["nameplateShowClassColor"] = "1",
["nameplateDefaultLargeFriendlyHeight"] = 64.125,
["npBorderTargetColor"] = false,
["npBorderClassColor"] = false,
["hideCastbarText"] = false,
["hpHeightEnemy"] = 10.8,
["arenaIndicatorModeTwo"] = false,
["nameplateEnemyWidthScale"] = 128,
["castBarEmphasisHeight"] = false,
["otherNpBuffFilterAll"] = false,
["castBarIconYPos"] = 0,
["hideFriendlyNameText"] = true,
["fakeNameAnchor"] = "BOTTOM",
["castBarShieldScale"] = 1,
["classIconBgOnly"] = false,
["nameplateAuraTypeGap"] = 0,
["hideDefaultPersonalNameplateAuras"] = false,
["npcTitleColor"] = false,
["partyPointerTestMode"] = false,
["personalNpBuffFilterBlizzard"] = true,
["friendlyNpBuffFilterOnlyMe"] = false,
["enableCastbarCustomization"] = true,
["nameplateKeyAurasHorizontalGap"] = 5,
["nameplateResourceYPos"] = 0,
["nameplateSelectedScale"] = 1.48,
["castBarBackgroundColor"] = {
0.33,
0.33,
0.33,
1,
},
["friendlyNameplatesOnlyInRaids"] = false,
["nameplateAuraSelfScale"] = 1,
["friendlyHealthBarColorPlayer"] = false,
["castBarNoInterruptColor"] = {
1,
0,
0.01568627543747425,
},
["guildNameScale"] = 1,
["friendlyNameplateTogglesUpdated"] = true,
["partyPointerShowOthersPets"] = false,
["friendlyHealthBarColorRGB"] = {
0,
1,
0,
},
["castBarInterruptHighlighterStartPercentageHeight"] = 15,
["classIndicatorHealer"] = false,
["hideNPCWhitelistOn"] = false,
["nameplateShowFriendlyPlayerGuardians"] = "0",
["nameplateOverlapHScale"] = 0.5,
["nameplateAuraTaller"] = false,
["classIndicatorOnlyFriends"] = false,
["petIndicatorYPos"] = 0,
["classIndicatorYPosYPos"] = -34,
["changeResourceStrata"] = false,
["showCircleOnArenaID"] = false,
["defaultLargeNamePlateFont"] = "Fonts\\FRIZQT__.TTF",
["enlargeAllCC"] = true,
["druidAlwaysShowCombos"] = false,
["nameplateVerticalPosition"] = 0,
["npcTitleColorRGB"] = {
1,
0.85,
0,
},
["arenaIdYPos"] = 0,
["dpsOrHealFullAggroColorRGB"] = {
1,
0,
0,
1,
},
["classIndicatorHighlight"] = true,
["nameplateFriendlyWidthScale"] = 60,
["petIndicatorColorHealthbar"] = false,
["npBorderTargetColorRGB"] = {
1,
1,
1,
1,
},
["classIndicatorSpecIcon"] = true,
["castBarInterruptHighlighterEndPercentageHeight"] = 85,
["castBarEmphasisSpark"] = false,
["absorbIndicator"] = false,
["totemIndicatorColorName"] = true,
["nameplateNonTargetAlpha"] = 1,
["nameplateAurasXPos"] = -1,
["hidePersonalManaFX"] = false,
["customFontSizeEnabled"] = false,
["partyPointerHideRaidmarker"] = true,
["alwaysShowPurgeTexture"] = true,
["castBarIconScale"] = 1.15,
["friendlyNpBuffFilterBlacklist"] = true,
["castBarHeightHeight"] = 9.3,
["castBarInterruptHighlighter"] = false,
["cleanedScaleScale"] = true,
["combatIndicatorEnemyOnly"] = false,
["fadeOutNPCsAlphaAlpha"] = 0.1000000014901161,
["totemIndicatorHideHealthBar"] = false,
["ccIconXPosXPos"] = -3,
["castBarIconAnchor"] = "LEFT",
["targetIndicatorColorNameplate"] = false,
["totemIndicatorScale"] = 1.13,
["updates"] = "v1.9.4b",
["nameplateLargerScale"] = "1.1",
["maxAurasOnNameplateScale"] = 10,
["healthNumbersTestMode"] = false,
["personalNpdeBuffEnable"] = false,
["hidePersonalBarExtraFrame"] = false,
["castBarEmphasisTextScale"] = 2,
["hideNpcMurlocYPos"] = 0,
["druidOverstacks"] = true,
["nameplateDefaultEnemyHeight"] = 45,
["npColorAuraBorder"] = false,
["buffIconScale"] = 1.65,
["otherNpBuffFilterWatchList"] = true,
["nameplateAuraPixelBorder"] = false,
["nameplateHorizontalPosition"] = 0,
["nameplateShowEnemyTotems"] = "1",
["focusTargetIndicatorColorNameplateRGB"] = {
1,
1,
1,
},
["nameplateShadowRGB"] = {
0,
0,
0,
1,
},
["nameplateTargetBorderSize"] = 3,
["showNameplateCastbarTimer"] = false,
["levelFrameFontSize"] = 12,
["partyPointerShowPet"] = true,
["nameplateExtraClickWidth"] = 0,
["partyIndicatorModeOff"] = true,
["ccIconScale"] = 1.34,
["otherNpdeBuffPandemicGlow"] = false,
["useCustomTextureForSelf"] = false,
["nameplatePersonalBorderSize"] = 1,
["useCustomTextureForFriendly"] = true,
["castBarShieldAnchor"] = "LEFT",
["showNameplateShadowOnlyTarget"] = false,
["castBarIconPixelBorder"] = false,
["enableNpNonTargetAlpha"] = false,
["executeIndicatorXPos"] = 0,
["healthNumbersCombined"] = false,
["partyPointerHighlightRGB"] = {
1,
0.71,
0,
},
["executeIndicatorYPos"] = 0,
["classIndicatorBackgroundRGB"] = {
0,
0,
0,
1,
},
["nameplateMinAlpha"] = 1,
["nameplateAuraRectangleSize"] = false,
["targetIndicatorHideIcon"] = false,
["showDefaultCooldownNumbersOnNpAuras"] = false,
["focusTargetIndicatorColorNameplate"] = false,
["reopenOptions"] = false,
["ccIconYPos"] = 29,
["friendlyNpdeBuffFilterBlacklist"] = false,
["enableNpVerticalPos"] = false,
["otherNpdeBuffFilterBlizzard"] = false,
["personalNpBuffFilterLessMinite"] = false,
["friendIndicator"] = false,
["targetIndicatorColorNameplateRGB"] = {
1,
0,
0.44,
},
["defaultLargeFontSize"] = 12,
["fixedFriendlyHealthbarHide"] = true,
["nameplateMaxAlphaScale"] = 1,
["keyAurasImportantBuffsEnabled"] = true,
["useFakeNameAnchorBottom"] = false,
["healthNumbersSwapped"] = false,
["ccIconXPos"] = -3,
["old_defaultLargeNamePlateFont"] = "Fonts\\FRIZQT__.TTF",
["enemyColorName"] = false,
["npBorderNonTargetColorRGB"] = {
0,
0,
0,
1,
},
["classIndicatorHideName"] = true,
["importantCCRootGlowRGB"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0.874,
["r"] = 1,
},
["auraWhitelist"] = {
{
["flags"] = {
["onlyMine"] = true,
["pandemic"] = false,
["important"] = false,
["enlarged"] = true,
["compacted"] = false,
},
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Adaptive Swarm",
["comment"] = "",
},
{
["flags"] = {
["compacted"] = false,
["important"] = true,
["enlarged"] = true,
["pandemic"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Attonement",
["comment"] = "",
},
{
["flags"] = {
["onlyMine"] = true,
["pandemic"] = false,
["important"] = false,
["enlarged"] = false,
["compacted"] = true,
},
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Crimson Tempest",
["comment"] = "",
},
{
["flags"] = {
["onlyMine"] = true,
["pandemic"] = false,
["important"] = true,
["enlarged"] = true,
["compacted"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Deathstalker's Mark",
["comment"] = "",
},
{
["flags"] = {
["onlyMine"] = true,
["pandemic"] = false,
["important"] = false,
["enlarged"] = true,
["compacted"] = false,
},
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Feral Frenzy",
["comment"] = "",
},
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Hex",
["comment"] = "",
},
{
["flags"] = {
["compacted"] = false,
["important"] = true,
["enlarged"] = true,
["pandemic"] = false,
},
["entryColors"] = {
["text"] = {
["a"] = 1,
["b"] = 1,
["g"] = 0.05098039656877518,
["r"] = 0.3843137621879578,
},
},
["comment"] = "",
["name"] = "Lifebloom",
},
{
["flags"] = {
["important"] = false,
["onlyMine"] = true,
["pandemic"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Moonfire",
["comment"] = "",
},
{
["flags"] = {
["compacted"] = false,
["important"] = true,
["enlarged"] = true,
["pandemic"] = false,
},
["entryColors"] = {
["text"] = {
["a"] = 1,
["b"] = 1,
["g"] = 0.05882353335618973,
["r"] = 0.4352941513061523,
},
},
["name"] = "Nullifying Shroud",
["comment"] = "",
},
{
["flags"] = {
["onlyMine"] = true,
["pandemic"] = false,
["important"] = false,
["enlarged"] = false,
["compacted"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Purge the wicked",
["comment"] = "",
},
{
["flags"] = {
["onlyMine"] = true,
["pandemic"] = false,
["important"] = false,
["enlarged"] = true,
["compacted"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Rake",
["comment"] = "",
},
{
["flags"] = {
["onlyMine"] = true,
["pandemic"] = false,
["important"] = false,
["enlarged"] = true,
["compacted"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Rip",
["comment"] = "",
},
{
["flags"] = {
["onlyMine"] = true,
["pandemic"] = false,
["important"] = false,
["enlarged"] = false,
["compacted"] = true,
},
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Rupture",
["comment"] = "",
},
{
["flags"] = {
["onlyMine"] = true,
["pandemic"] = false,
["important"] = false,
["enlarged"] = false,
["compacted"] = true,
},
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Sepsis",
["comment"] = "",
},
{
["flags"] = {
["onlyMine"] = true,
["pandemic"] = false,
["important"] = false,
["enlarged"] = false,
["compacted"] = true,
},
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Shiv",
["comment"] = "",
},
{
["flags"] = {
["pandemic"] = false,
["important"] = true,
["enlarged"] = true,
["compacted"] = false,
},
["entryColors"] = {
["text"] = {
["a"] = 1,
["r"] = 1,
["g"] = 0,
["b"] = 0.1176470667123795,
},
},
["name"] = "Thoughtsteal",
["comment"] = "",
},
{
["flags"] = {
["onlyMine"] = true,
["pandemic"] = false,
["important"] = false,
["enlarged"] = true,
["compacted"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Thrash",
["comment"] = "",
},
},
["exportVersion"] = "BBP: 1.9.3e WoW: 12.0.0",
["castBarRecolorInterrupt"] = false,
["castBarEmphasisSelfColorRGB"] = {
1,
0,
0,
},
["nameplateShadowHighlightRGB"] = {
1,
1,
1,
1,
},
["totemListUpdateTWW4"] = true,
["castBarHeight"] = 9.3,
["importantBuffsOffensives"] = true,
["nameplateResourceDoNotRaiseAuras"] = false,
["nameplateMotion"] = "1",
["classIndicatorFriendlyXPos"] = 0,
["instantComboPoints"] = false,
["auraWhitelistAlphaUpdated"] = true,
["removeRealmNames"] = true,
["absorbIndicatorScale"] = 1,
["disableImportantAurasOnSelf"] = false,
["personalNpTRP3Color"] = false,
["nameplateAuraSquare"] = true,
["fadeOutNPCsWhitelist"] = {
{
["id"] = 104818,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Ancestral Protection Totem",
["comment"] = "",
},
{
["id"] = 61245,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Capacitor Totem",
["comment"] = "",
},
{
["id"] = 78001,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Cloudburst Totem",
["comment"] = "",
},
{
["id"] = 105451,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Counterstrike Totem",
["comment"] = "",
},
{
["id"] = 2630,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Earthbind Totem",
["comment"] = "",
},
{
["id"] = 100943,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Earthen Wall Totem",
["comment"] = "",
},
{
["id"] = 60561,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Earthgrab Totem",
["comment"] = "",
},
{
["id"] = 17252,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Felguard (Demo Pet)",
["comment"] = "",
},
{
["id"] = 417,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Felhunter (Warlock)",
["comment"] = "",
},
{
["id"] = 5925,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Grounding Totem",
["comment"] = "",
},
{
["id"] = 114565,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Guardian Queen (prot pala)",
["comment"] = "",
},
{
["id"] = 3527,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Healing Stream Totem",
["comment"] = "",
},
{
["id"] = 59764,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Healing Tide Totem",
["comment"] = "",
},
{
["id"] = 165189,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Hunter Pet (they all have same ID)",
["comment"] = "",
},
{
["id"] = 89,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Infernal (Warlock)",
["comment"] = "",
},
{
["id"] = 97369,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Liquid Magma Totem",
["comment"] = "",
},
{
["id"] = 10467,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Mana Tide Totem",
["comment"] = "",
},
{
["id"] = 62982,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Mindbender",
["comment"] = "",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 69792,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Monk Image (Green)",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 69791,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Monk Image (Red)",
},
{
["id"] = 107100,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Observer (Warlock)",
["comment"] = "",
},
{
["id"] = 5923,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Poison Cleansing Totem",
["comment"] = "",
},
{
["id"] = 101398,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Psyfiend (Spriest)",
["comment"] = "",
},
{
["id"] = 225672,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Shadow (Priest Re-Fear)",
["comment"] = "",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 19668,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Shadowfiend",
},
{
["id"] = 53006,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Spirit Link Totem",
["comment"] = "",
},
{
["id"] = 179867,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Static Field Totem",
["comment"] = "",
},
{
["id"] = 59712,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Stone Bulwark Totem",
["comment"] = "",
},
{
["id"] = 194117,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Stoneskin Totem",
["comment"] = "",
},
{
["id"] = 1863,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Succubus (Warlock)",
["comment"] = "",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 225409,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Surging Totem",
},
{
["id"] = 105427,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Totem of Wrath",
["comment"] = "",
},
{
["id"] = 194118,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Tranquil Air Totem",
["comment"] = "",
},
{
["id"] = 5913,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Tremor Totem",
["comment"] = "",
},
{
["id"] = 135002,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Tyrant (Warlock)",
["comment"] = "",
},
{
["flags"] = {
["murloc"] = false,
},
["comment"] = "",
["id"] = 224466,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Voidwrath (Priest)",
},
{
["id"] = 119052,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "War Banner",
["comment"] = "",
},
{
["id"] = 97285,
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Wind Rush Totem",
["comment"] = "",
},
},
["hpHeightFriendly"] = 10.8,
["anonMode"] = false,
["auraColorPvEOnly"] = false,
["enemyHealthBarColorNpcOnly"] = false,
["nameplateShowFriendlyPets"] = "0",
["friendlyNpdeBuffFilterLessMinite"] = false,
["totemListUpdateTWW3"] = true,
["castBarEmphasisHealthbarColor"] = false,
["personalBarPosition"] = 0.5,
["healthNumbersOnlyInCombat"] = false,
["totemListUpdateTWW2"] = true,
["nameplateAurasPersonalXPos"] = 0,
["nameplateKeyAurasYPos"] = 0,
["customTextureSelfMana"] = "Solid",
["customFontSize"] = 12,
["hideEliteDragon"] = true,
["nameplateResourceUnderCastbar"] = false,
["castBarDragonflightShield"] = true,
["raidmarkerPvPOnly"] = false,
["nameplateAuraWidthGap"] = 1,
["nameplateOverlapV"] = 0.5,
["nameplateMinAlphaScale"] = 1,
["npBorderFocusColorRGB"] = {
0,
0,
0,
1,
},
["classIndicatorCCAuras"] = true,
["personalBarTweaks"] = false,
["partyPointerYPos"] = -40,
["nameplateAuraKeyAuraPositionEnabled"] = false,
["bgIndicatorAnchor"] = "BOTTOM",
["healthNumbersScale"] = 1.01,
["castBarShieldYPos"] = 0,
["totemIndicatorHideAuras"] = true,
["useCustomTextureForSelfMana"] = false,
["nameplateDefaultLargeEnemyHeight"] = 64.125,
["hideNpcCastbar"] = false,
["NamePlateVerticalScale"] = 4,
["otherNpBuffEnable"] = true,
["raidmarkIndicatorRaiseStrata"] = false,
["castBarInterruptHighlighterStartTime"] = 0.8,
["hideCastbarWhitelistOn"] = false,
["importantBuffsMobilityGlow"] = true,
["classIndicatorTank"] = true,
["tankNoAggroColorRGB"] = {
1,
0,
0,
1,
},
["buffIconYPos"] = 0,
["hideTempHpLoss"] = false,
["customFontOutline"] = "THINOUTLINE",
["nameplateCenterAllRows"] = true,
["healthNumbersCurrentFull"] = false,
["classIndicatorBackground"] = true,
["classIndicatorHighlightColor"] = false,
["enemyColorThreatHideSolo"] = false,
["smallPetsInPvP"] = false,
["useCustomTextureForExtraBars"] = true,
["importantCCSilenceGlow"] = true,
["enemyColorThreat"] = false,
["enemyColorNameRGB"] = {
1,
1,
1,
},
["friendlyNpBuffPurgeGlow"] = false,
["personalNpdeBuffFilterLessMinite"] = false,
["friendlyNpBuffEmphasisedBorder"] = false,
["blizzardDefaultFilterOnlyMine"] = false,
["partyIDScale"] = 1,
["nameplateMinAlphaDistance"] = 60,
["executeIndicatorPercentSymbol"] = false,
["nameplateGeneralHpHeight"] = 21.5,
["buffIconXPos"] = 0,
["petIndicator"] = true,
["enemyNameplateHealthbarHeight"] = 10.8,
["totemIndicatorXPos"] = 0,
["customFont"] = "Friz Quadrata TT",
["nameplateSelfHeight"] = 45.0000114440918,
["friendlyNpdeBuffFilterAll"] = false,
["fakeNameAnchorRelative"] = "TOP",
["healthNumbersPlayers"] = true,
["importantCCFullGlowRGB"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0.874,
["r"] = 1,
},
["friendlyNameScale"] = 1,
["showCastBarIconWhenNoninterruptible"] = true,
["personalNpBuffEnable"] = false,
["classIndicatorYPos"] = -34,
["nameplateDefaultFriendlyHeight"] = 45,
["hideNPCPetsOnly"] = false,
["nameplateDefaultLargeEnemyWidth"] = 154,
["old_defaultNamePlateFontFlags"] = "",
["executeIndicatorInRangeColor"] = false,
["nameplateAuraCompactedScale"] = 0.98,
["totemIndicatorAnchor"] = "TOP",
["partyPointerHealerReplace"] = true,
["totemIndicatorYPos"] = 0,
["friendlyHideHealthBar"] = true,
["hideCastbarIcon"] = false,
["tankLosingAggroColorRGB"] = {
1,
0.47,
0,
1,
},
["classicRetailNameplates"] = true,
["bgIndicatorScale"] = 1,
["defaultNamePlateFontFlags"] = "SLUG",
["fadeOutNPCsAlpha"] = 0.1000000014901161,
["nameplateExtraClickHeight"] = 0,
["castBarRecolor"] = false,
["castBarChanneledColor"] = {
0.4862745404243469,
1,
0.294117659330368,
1,
},
["otherNpBuffFilterBlacklist"] = true,
["combatIndicator"] = false,
["nameplateShowFriendlyPlayerPets"] = "0",
["nameplateMaxScale"] = 1.25,
["npAuraOtherRGB"] = {
0,
0,
0,
},
["nameplateMotionSpeed"] = 0.03,
["totemIndicatorNoAnimation"] = true,
["bgIndicatorShowFlags"] = true,
["classIndicatorHideFriendlyHealthbar"] = true,
["classIndicatorFriendlyYPos"] = -31,
["friendlyColorName"] = false,
["healthNumbersNpcs"] = true,
["healerIndicatorBgOnly"] = true,
["hideNameDuringCast"] = false,
["fadeOutNPCOnlyFadeSecondaryPets"] = true,
["guildNameColorRGB"] = {
0,
1,
0,
},
["classIndicatorEnemy"] = true,
["customTextureSelf"] = "Solid",
["sortDurationAuras"] = false,
["defaultFontSize"] = 9,
["combatIndicatorAnchor"] = "CENTER",
["nameplateAuraHeightGap"] = 2,
["friendlyNameplateNonstackable"] = false,
["hideNPC"] = true,
["importantBuffsMobilityGlowRGB"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 0,
},
["executeIndicatorAnchor"] = "LEFT",
["nameplateBorderSize"] = 1,
["nameplateAuraBuffSelfScale"] = 1.1,
["npAuraBuffsRGB"] = {
0,
0.67,
1,
},
["totemIndicatorDefaultCooldownTextSizeScale"] = 0.96,
["enableNpNonTargetAlphaFullAlphaCasting"] = false,
["normalCastbarForEmpoweredCasts"] = true,
["executeIndicatorFriendly"] = false,
["nameplateAuraDebuffSelfScale"] = 1.1,
["healerIndicatorEnemyYPos"] = 0,
["importantCCFullGlow"] = true,
["showInterruptsOnNameplateAuras"] = true,
["combatIndicatorPlayersOnly"] = false,
["highlightNpShadowOnMouseover"] = false,
["friendlyNameColor"] = false,
["hideResourceFrame"] = false,
["totemIndicatorDefaultCooldownTextSize"] = 0.96,
["nameplateMinAlphaDistanceScale"] = 60,
["arenaModeSettingKey"] = "1: Replace name with Arena ID",
["totemIndicatorEnemyOnly"] = true,
["defaultNamePlateFont"] = "Fonts\\FRIZQT__.TTF",
["useCustomTextureForEnemy"] = true,
["targetIndicatorAnchor"] = "TOP",
["combatIndicatorArenaOnly"] = false,
["nameplateOverlapH"] = 0.5,
["castbarEventsOn"] = false,
["focusTargetIndicatorYPos"] = 0,
["classIndicatorUpdated2"] = true,
["executeIndicatorInRangeColorRGB"] = {
0,
1,
0.8,
1,
},
["healerIndicatorEnemyScale"] = 1,
["classIndicatorOnlyParty"] = false,
["useCustomCastbarBGTexture"] = false,
["classIndicatorFriendly"] = true,
["nameplateShowFriendlyClassColor"] = "1",
["friendlyHideHealthBarNpc"] = true,
["nameplateNonTargetAlphaScale"] = 1,
["castBarFullTextWidth"] = false,
["fakeNameYPos"] = 0,
["personalNpdeBuffFilterAll"] = false,
["executeIndicatorTargetOnly"] = false,
["partyPointerHighlight"] = false,
["totemIndicatorTestMode"] = false,
["focusTargetIndicatorColorName"] = false,
["totemIndicatorGlowOff"] = false,
["importantBuffsDefensivesGlow"] = true,
["nameplateShowEnemyPets"] = "1",
["nameplateAuraScale"] = 1,
["npBorderNeutralColorRGB"] = {
1,
1,
0,
1,
},
["enemyHealthBarColorRGB"] = {
1,
0,
0,
},
["targetIndicatorXPos"] = 0,
["nameplateResourcePositionFix"] = true,
["fakeNameXPos"] = 0,
["wasOnLoadingScreen"] = true,
["keyAurasImportantGlowOn"] = true,
["importantBuffsOffensivesGlow"] = true,
["importantBuffsOffensivesGlowRGB"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0.5,
["r"] = 1,
},
["nameplateMaxAlphaDistanceScale"] = 60,
["nameplateKeyAurasXPos"] = 0,
["combatIndicatorScale"] = 0.1,
["personalNpBuffFilterAll"] = false,
["castbarQuickHide"] = true,
["healerIndicatorArenaOnly"] = true,
["guildNameColor"] = false,
["castBarInterruptHighlighterDontInterruptRGB"] = {
0,
1,
0.8784314393997192,
1,
},
["nameplateAuraEnlargedSquare"] = true,
["nameplateAuraDebuffScale"] = 1.1,
["executeIndicatorUseTexture"] = false,
["npAuraPoisonRGB"] = {
0,
0.52,
0.031,
},
["focusTargetIndicatorXPos"] = 0,
["nameplateAurasFriendlyCenteredAnchor"] = true,
["enemyNameScale"] = 1,
["partyIndicatorModeFour"] = false,
["colorNpcList"] = {
},
["raidmarkIndicatorScale"] = 1,
["friendlyNpdeBuffEnable"] = true,
["arenaIndicatorModeFive"] = false,
["npcTitleScale"] = 1,
["partyPointerOnlyParty"] = false,
["nameplateAuraPlayersOnly"] = false,
["enableCastbarEmphasis"] = false,
["healerIndicator"] = true,
["partyPointerHealer"] = false,
["useFakeName"] = true,
["combatIndicatorYPos"] = 0,
["classIndicatorFriendlyYPosYPos"] = -31,
["healerIndicatorXPos"] = 0,
["importantCCRoot"] = true,
["hideTargetHighlight"] = true,
["nameplateShowFriendlyPlayerTotems"] = "1",
["friendlyNameplateClickthrough"] = true,
["healthNumbersTargetOnly"] = false,
["healthNumbersPercentSymbol"] = true,
["hideNPCSecondaryShowMurloc"] = true,
["totemIndicatorColorHealthBar"] = true,
["arenaIndicatorTestMode"] = false,
["bgIndicatorTestMode"] = false,
["nameplateAurasCenteredAnchor"] = false,
["healthNumbersClassColor"] = false,
["nameplateDefaultLargeFriendlyWidth"] = 154,
["importantBuffsMobility"] = true,
["personalNpdeBuffFilterWatchList"] = true,
["partyPointerTargetIndicator"] = true,
["fakeNameFriendlyYPos"] = 0,
["classIconAlwaysShowHealer"] = false,
["npAuraMagicRGB"] = {
0.13,
0.44,
1,
},
["onlyShowInterruptableCasts"] = false,
["classIndicatorAlpha"] = 1,
["castBarShieldXPos"] = 0,
["largeNameplates"] = true,
["absorbIndicatorEnemyOnly"] = false,
["hideNPCAllNeutral"] = false,
["changeNameplateBorderSize"] = false,
["otherNpBuffBlueBorder"] = false,
["healthNumbers"] = true,
["showLastNameNpc"] = false,
["onlyPandemicAuraMine"] = true,
["nameplateShowEnemyMinions"] = "1",
["targetIndicatorTestMode"] = false,
["raidmarkIndicatorFullAlpha"] = true,
["healthNumbersAnchor"] = "CENTER",
["petIndicatorAnchor"] = "CENTER",
["enlargeAllImportantBuffs"] = true,
["importantCCFull"] = true,
["setCVarAcrossAllCharacters"] = true,
["classIconSquareBorderFriendly"] = true,
["importantBuffsDefensivesGlowRGB"] = {
["a"] = 1,
["b"] = 0.945,
["g"] = 0.662,
["r"] = 1,
},
["friendlyNpBuffFilterAll"] = false,
["testAllEnabledFeatures"] = false,
["classIconHealerIconType"] = 2,
["classIndicatorFriendlyAnchor"] = "TOP",
["partyPointerHealerScale"] = 1,
["executeIndicatorAlwaysOn"] = false,
["nameplateDefaultEnemyWidth"] = 110,
["personalNpdeBuffFilterBlacklist"] = true,
["bgIndicatorEnemyOnly"] = true,
["changeNpHpBgColorSolid"] = false,
["friendlyColorNameRGB"] = {
1,
1,
1,
},
["healerIndicatorEnemyAnchor"] = "TOPRIGHT",
["partyIndicatorModeTwo"] = false,
["nameplateAuraCountScale"] = 1.1,
["combatIndicatorSap"] = false,
["executeIndicatorNotOnFullHp"] = false,
["focusTargetIndicatorAnchor"] = "TOPRIGHT",
["nameplateDebuffPadding"] = "0",
["nameplateAuraPlayersOnlyShowTarget"] = false,
["enableNpNonTargetAlphaTargetOnly"] = false,
["targetIndicatorTexture"] = "Blizzard DF",
["raidmarkIndicator"] = false,
["petIndicatorTestMode"] = false,
["friendlyNpBuffBlueBorder"] = false,
["friendlyNpBuffFilterImportantBuffs"] = false,
["nameplateDefaultFriendlyWidth"] = 110,
["npAuraCurseRGB"] = {
0.47,
0,
0.78,
},
["absorbIndicatorYPos"] = 0,
["healerIndicatorTestMode"] = false,
["recolorTempHpLoss"] = false,
["questIndicatorScale"] = 1,
["targetNameplateAuraScale"] = 1,
["totemListUpdateTWW1"] = true,
["fadeOutNPCWhitelistOn"] = false,
["totemIndicator"] = true,
["bgIndicatorYPos"] = 0,
["customCastbarNonInterruptibleTexture"] = "Blizzard RetailBar",
["castBarCastColor"] = {
0.4862745404243469,
1,
0.294117659330368,
1,
},
["personalNpBuffFilterBlacklist"] = true,
["classIndicatorAlwaysShowPet"] = false,
["nameplateOverlapVScale"] = 0.5,
["healthNumbersPercentage"] = true,
["useCustomFont"] = false,
["raidmarkIndicatorYPos"] = 0,
["focusTargetIndicatorScale"] = 1,
["personalNpdeBuffFilterCC"] = false,
["showNameplateTargetText"] = false,
["hideNpAuraSwipe"] = false,
["showTotemIndicatorCooldownSwipe"] = true,
["nameplateResourceXPos"] = 0,
["friendlyNameplatesOnlyInDungeons"] = false,
["classIndicatorXPosXPos"] = -48,
["hideNPCHideOthersPets"] = true,
["partyPointerAnchor"] = "TOP",
["customTexture"] = "Blizzard",
["hpHeightSelf"] = 10.8,
["enemyClassColorName"] = true,
["nameplateSelfAlpha"] = "0.89999997615814",
["fakeNameFriendlyXPos"] = 0,
["old_defaultNamePlateFont"] = "Fonts\\FRIZQT__.TTF",
["absorbIndicatorAnchor"] = "LEFT",
["nameplateAuraTestMode"] = false,
["personalNpBuffFilterWatchList"] = true,
["petIndicatorShowMurloc"] = true,
["classIconSquareBorder"] = true,
["hideCastbarEnemy"] = false,
["useCustomTextureForBars"] = false,
["friendlyHealthBarColor"] = false,
["importantCCSilenceGlowRGB"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0.874,
["r"] = 1,
},
["partyPointerBgOnly"] = false,
["threatColorAlwaysOn"] = false,
["absorbIndicatorTestMode"] = false,
["classIconEnemyHealIcon"] = true,
["bgIndicatorXPos"] = 0,
["healthNumbersJustify"] = "CENTER",
["classIconAlwaysShowBgObj"] = true,
["hideCastbarBorderShield"] = false,
["nameplateStyle"] = "0",
["tankOffTankAggroColorRGB"] = {
0,
0.95,
1,
1,
},
["nameplateMotionSpeedScale"] = 0.03,
["hideCastbarFriendly"] = false,
["healthNumbersHideSelf"] = false,
["changeNpHpBgColor"] = false,
["totemListUpdateTWW5"] = true,
["classIndicatorOnlyHealer"] = false,
["disableEnlargedAurasOnSelf"] = false,
["nameplateCastbarTestMode"] = false,
["arenaIDScale"] = 1,
["focusTargetIndicator"] = false,
["toggleNamesOffDuringPVE"] = false,
["arenaIndicatorModeFour"] = false,
["executeIndicatorTestMode"] = false,
["classIndicatorBackgroundSize"] = 1,
["friendlyNpdeBuffFilterOnlyMe"] = false,
["nameplateKeyAurasAnchor"] = "RIGHT",
["nameplateAurasPersonalCenteredAnchor"] = true,
["importantCCDisarmGlowRGB"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0.874,
["r"] = 1,
},
["partyPointerScale"] = 1,
["arenaSpecYPos"] = 0,
["fadeOutNPCsList"] = {
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Abomination",
["comment"] = "",
},
{
["id"] = 24207,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Army of the Dead",
["comment"] = "",
},
{
["id"] = 62005,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Beast (Hunter)",
["comment"] = "",
},
{
["id"] = 226269,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Charhound (Warlock)",
["comment"] = "",
},
{
["id"] = 136408,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Darkhound",
["comment"] = "",
},
{
["id"] = 105419,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Dire Basilisk (Hunter)",
["comment"] = "",
},
{
["id"] = 26125,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "DK pet",
["comment"] = "",
},
{
["id"] = 95072,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Earth Elemental (Shaman)",
["comment"] = "",
},
{
["id"] = 228224,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Fenryr (Hunter)",
["comment"] = "",
},
{
["id"] = 226268,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Gloomhound (Warlock)",
["comment"] = "",
},
{
["id"] = 228226,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Hati (Hunter)",
["comment"] = "",
},
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "High Inquisitor Whitemane",
["comment"] = "",
},
{
["flags"] = {
["important"] = false,
["pandemic"] = false,
},
["entryColors"] = {
["text"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0,
},
},
["name"] = "Highlord Darion Mograine",
["comment"] = "",
},
{
["id"] = 136398,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Illidari Satyr",
["comment"] = "",
},
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "King Thoras Trollbane",
["comment"] = "",
},
{
["id"] = 163366,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Magus(Army of the Dead)",
["comment"] = "",
},
{
["id"] = 31216,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Mirror Images (Mage)",
["comment"] = "",
},
{
["id"] = 221632,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Mograine (DK)",
["comment"] = "",
},
{
["id"] = 69792,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Monk SEF Image (Green)",
["comment"] = "",
},
{
["id"] = 69791,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Monk SEF Image (Red)",
["comment"] = "",
},
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Nazgrim",
["comment"] = "",
},
{
["id"] = 221634,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Nazgrim (DK)",
["comment"] = "",
},
{
["id"] = 29264,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Spirit Wolves (Enha Shaman)",
["comment"] = "",
},
{
["id"] = 54983,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Treant",
["comment"] = "",
},
{
["id"] = 103822,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Treant",
["comment"] = "",
},
{
["id"] = 221635,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Trollbane (DK)",
["comment"] = "",
},
{
["id"] = 135816,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Vilefiend (Warlock)",
["comment"] = "",
},
{
["id"] = 192337,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Void Tendril (Spriest)",
["comment"] = "",
},
{
["id"] = 136403,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
},
["name"] = "Void Terror",
["comment"] = "",
},
{
["id"] = 208441,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Water Elemental (Mage)",
["comment"] = "",
},
{
["id"] = 221633,
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Whitemane (DK)",
["comment"] = "",
},
{
["flags"] = {
["pandemic"] = false,
["important"] = false,
},
["entryColors"] = {
["text"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["name"] = "Xuen",
["comment"] = "",
},
},
["petIndicatorColorHealthbarRGB"] = {
0.03,
0.35,
0,
},
["otherNpBuffPurgeGlow"] = false,
["friendlyNpBuffEnable"] = false,
["version"] = "1.00",
["arenaIdAnchorRaiseStrata"] = false,
["hideCastbar"] = false,
["petIndicatorXPos"] = 0,
["hasSaved"] = true,
["targetHighlightFix"] = true,
["keepNpShadowTargetHighlighted"] = false,
["useCustomCastbarTexture"] = false,
["showNameplateShadow"] = false,
["overShields"] = true,
["dpsOrHealTargetAggroColorRGB"] = {
1,
0,
0,
1,
},
["classIndicatorXPos"] = -48,
["friendlyHealthBarColorNpc"] = false,
["defaultNpAuraCdSize"] = 0.5,
["nameplateGlobalScale"] = "1.0",
["nameplateAuraAnchor"] = "BOTTOMLEFT",
["customCastbarTexture"] = "Blizzard",
["ghostAuras"] = {
},
["nameplateAuraRowFriendlyAmount"] = 5,
["nameplateMaxAlphaDistance"] = 60,
["castBarIconXPosXPos"] = 5,
["partyPointerClassColor"] = true,
["buffIconAnchor"] = "LEFT",
["executeIndicator"] = false,
["fakeNameScaleWithParent"] = false,
["partyPointerHighlightScale"] = 1,
["partyPointerTexture"] = 1,
["nameplateAurasXPosXPos"] = -1,
["friendlyNpdeBuffFilterBlizzard"] = false,
["arenaIndicatorModeOne"] = true,
["enableNpNonFocusAlpha"] = false,
["healerIndicatorEnemyXPos"] = 0,
["nameplateAuraBuffScale"] = 1.1,
["onlyShowHighlightedNpShadow"] = false,
["maxAurasOnNameplate"] = 10,
["friendlyNameplatesOnlyInArena"] = true,
["firstSaveComplete"] = true,
["nameplateAuraHideCooldownNumbers"] = false,
}
BBPCVarBackupsDB = {
["nameplateStyle"] = "0",
["nameplateAuraScale"] = "1",
["nameplateMaxScale"] = "0.576",
["nameplateMaxAlpha"] = "1.0",
["nameplateOverlapV"] = "0.5",
["nameplateShowFriendlyPlayerTotems"] = "1",
["nameplateShowEnemyMinions"] = "0",
["nameplateShowEnemyPets"] = "0",
["nameplateShowFriendlyNPCs"] = "0",
["nameplateSelectedScale"] = "0.98",
["nameplateOverlapH"] = "0.5",
["nameplateShowEnemyMinus"] = "0",
["nameplateShowFriendlyPlayerGuardians"] = "0",
["nameplateMinAlpha"] = "1",
["nameplatePlayerLargerScale"] = "1",
["nameplateMaxAlphaDistance"] = "60",
["nameplateShowEnemyTotems"] = "1",
["nameplateLargerScale"] = "1",
["nameplateDebuffPadding"] = "0",
["nameplateShowFriendlyPlayerMinions"] = "0",
["nameplateMinScale"] = "0.576",
["nameplateOccludedAlphaMult"] = "1",
["nameplateShowClassColor"] = "1",
["nameplateShowAll"] = "1",
["nameplateSelfAlpha"] = "0.89999997615814",
["nameplateMinAlphaDistance"] = "60",
["nameplateShowEnemyGuardians"] = "0",
["nameplateShowFriendlyPlayerPets"] = "0",
["nameplateShowFriendlyClassColor"] = "0",
}
