
Details_StreamerDB = {
["characters"] = {
["Hystoricall - Tichondrius"] = "Mysticallx - Sargeras",
["Justinjames - Sentinels"] = "Mysticallx - Sargeras",
["Mstcll - Borean Tundra"] = "Mysticallx - Sargeras",
["Mstcll - Garrosh"] = "Mysticallx - Sargeras",
["Onlyplaypala - Sargeras"] = "Mysticallx - Sargeras",
["Onlyplaymage - Sargeras"] = "Mysticallx - Sargeras",
["Réðçräñé - Sargeras"] = "Mysticallx - Sargeras",
["Representing - Area 52"] = "Mysticallx - Sargeras",
["Lotusflowers - Sargeras"] = "Mysticallx - Sargeras",
["Nerfmw - Moon Guard"] = "Mysticallx - Sargeras",
["Vivifying - Sentinels"] = "Mysticallx - Sargeras",
["Mysticallx - Tichondrius"] = "Mysticallx - Sargeras",
["Flowerlotus - Sentinels"] = "Mysticallx - Sargeras",
["Mw - Tichondrius"] = "Mysticallx - Sargeras",
["Mystweaver - Area 52"] = "Mysticallx - Sargeras",
["Cocoonjkdead - Sentinels"] = "Mysticallx - Sargeras",
["Chithion - Zul'jin"] = "Mysticallx - Sargeras",
["Mysticall - Bleeding Hollow"] = "Mysticallx - Sargeras",
["Harambad - Sargeras"] = "Mysticallx - Sargeras",
["Onlyplaydh - Sargeras"] = "Mysticallx - Sargeras",
["Gréëñðrägoñ - Sargeras"] = "Mysticallx - Sargeras",
["Trialfornowa - Cenarius"] = "Mysticallx - Sargeras",
["Yungmyst - Sentinels"] = "Mysticallx - Sargeras",
["Gréëñðrägøñ - Sargeras"] = "Mysticallx - Sargeras",
["Mysticbankk - Area 52"] = "Mysticallx - Sargeras",
["Mysticall - Moon Guard"] = "Mysticallx - Sargeras",
["Enveloping - Area 52"] = "Mysticallx - Sargeras",
["Justinjames - Sargeras"] = "Mysticallx - Sargeras",
["Mysticallxd - Sargeras"] = "Mysticallx - Sargeras",
["Darkapostle - Tichondrius"] = "Mysticallx - Sargeras",
["Coocoocachu - Sargeras"] = "Mysticallx - Sargeras",
["Jayjay - Detheroc"] = "Mysticallx - Sargeras",
["Zft - Sentinels"] = "Mysticallx - Sargeras",
["Buffmwpls - Sargeras"] = "Mysticallx - Sargeras",
["Onlyplaymonk - Sargeras"] = "Mysticallx - Sargeras",
["Yungmyst - Sargeras"] = "Mysticallx - Sargeras",
["Cocoonjkdead - Bleeding Hollow"] = "Mysticallx - Sargeras",
["Mysticallx - Area 52"] = "Mysticallx - Sargeras",
["Onlyplayfury - Sargeras"] = "Mysticallx - Sargeras",
["Soullkeeper - Tichondrius"] = "Mysticallx - Sargeras",
["Ashdfh - Mythic Dungeon Heroes - US"] = "Mysticallx - Sargeras",
["Mwreroll - Sargeras"] = "Mysticallx - Sargeras",
["Mysticall - Sentinels"] = "Mysticallx - Sargeras",
["Mysticbankk - Sargeras"] = "Mysticallx - Sargeras",
["Soullstëaler - Sentinels"] = "Mysticallx - Sargeras",
["Enveloping - Sentinels"] = "Mysticallx - Sargeras",
["Mysticbankk - Sentinels"] = "Mysticallx - Sargeras",
["Mysticbankk - Tichondrius"] = "Mysticallx - Sargeras",
["Iamdeadinsid - Sentinels"] = "Mysticallx - Sargeras",
["Moosticall - Sentinels"] = "Mysticallx - Sargeras",
["Healjkoom - Sargeras"] = "Mysticallx - Sargeras",
["Mstcll - Aerie Peak"] = "Mysticallx - Sargeras",
["Sevenseconds - Area 52"] = "Mysticallx - Sargeras",
["Coccoon - Area 52"] = "Mysticallx - Sargeras",
["Mediumvibes - Sentinels"] = "Mysticallx - Sargeras",
["Soullkeeper - Sargeras"] = "Mysticallx - Sargeras",
["Bovadeez - Bleeding Hollow"] = "Mysticallx - Sargeras",
["Representing - Sargeras"] = "Mysticallx - Sargeras",
["Stylle - Sentinels"] = "Mysticallx - Sargeras",
["Onlyplaymonk - Area 52"] = "Mysticallx - Sargeras",
["Vivifying - Area 52"] = "Mysticallx - Sargeras",
["Weavethemist - Sargeras"] = "Mysticallx - Sargeras",
["Onlyplaydru - Sargeras"] = "Mysticallx - Sargeras",
["Réðçräñé - Sentinels"] = "Mysticallx - Sargeras",
["Mstcll - Blackwater Raiders"] = "Mysticallx - Sargeras",
["Hystoricall - Sentinels"] = "Mysticallx - Sargeras",
["Mysticallx - Sargeras"] = "Mysticallx - Sargeras",
["Mysticbollt - Garrosh"] = "Mysticallx - Sargeras",
["Rsk - Sentinels"] = "Mysticallx - Sargeras",
["Mstcll - Area 52"] = "Mysticallx - Sargeras",
["Mysticallxy - Area 52"] = "Mysticallx - Sargeras",
["Lifedestroys - Tichondrius"] = "Mysticallx - Sargeras",
["Mstcll - Echo Isles"] = "Mysticallx - Sargeras",
["Cocoonjkdead - Aerie Peak"] = "Mysticallx - Sargeras",
["Hydraxises - Lightning's Blade"] = "Mysticallx - Sargeras",
["Mysticallx - Emerald Dream"] = "Mysticallx - Sargeras",
["Representing - Blackhand"] = "Mysticallx - Sargeras",
["Thunderbad - Sentinels"] = "Mysticallx - Sargeras",
["Yungmyst - Area 52"] = "Mysticallx - Sargeras",
["Onlyplaysub - Sargeras"] = "Mysticallx - Sargeras",
["Mstcll - Sentinels"] = "Mysticallx - Sargeras",
["Vezimmarr - Aerie Peak"] = "Mysticallx - Sargeras",
["Mstcll - Sargeras"] = "Mysticallx - Sargeras",
["Sevenseconds - Sargeras"] = "Mysticallx - Sargeras",
["Ggs - Detheroc"] = "Mysticallx - Sargeras",
["Misstickle - Sargeras"] = "Mysticallx - Sargeras",
["Nightbllade - Area 52"] = "Mysticallx - Sargeras",
["Kickthesun - Sargeras"] = "Mysticallx - Sargeras",
["Nerfmw - Sargeras"] = "Mysticallx - Sargeras",
["Cocoonjkdead - Area 52"] = "Mysticallx - Sargeras",
},
["profiles"] = {
["Mysticallx - Sargeras"] = {
["font_color"] = {
1,
1,
1,
1,
},
["is_first_run"] = false,
["grow_direction"] = "right",
["arrow_color"] = {
1,
1,
1,
0.5,
},
["main_frame_size"] = {
300,
500.000030517578,
},
["arrow_anchor_y"] = 0,
["minimap"] = {
["minimapPos"] = 160,
["radius"] = 160,
["hide"] = true,
},
["main_frame_locked"] = false,
["arrow_anchor_x"] = 0,
["row_color"] = {
0.1,
0.1,
0.1,
0.4,
},
["row_texture"] = "Details Serenity",
["square_grow_direction"] = "right",
["use_spark"] = true,
["author"] = "Details! Team",
["square_amount"] = 5,
["enabled"] = false,
["arrow_size"] = 10,
["per_second"] = {
["enabled"] = false,
["point"] = "CENTER",
["scale"] = 1,
["font_shadow"] = true,
["y"] = 3.0517578125e-05,
["x"] = 3.0517578125e-05,
["attribute_type"] = 1,
["update_speed"] = 0.05,
["size"] = 32,
},
["row_spacement"] = 21,
["main_frame_color"] = {
0,
0,
0,
0.2,
},
["main_frame_strata"] = "LOW",
["arrow_texture"] = "Interface\\CHATFRAME\\ChatFrameExpandArrow",
["y"] = 4.57763671875e-05,
["font_size"] = 10,
["x"] = 0,
["font_face"] = "Friz Quadrata TT",
["square_size"] = 32,
["use_square_mode"] = false,
["scale"] = 1,
["row_height"] = 20,
["point"] = "CENTER",
},
},
}
