
DiminishDB = {
["profileKeys"] = {
["Mwreroll-Sargeras"] = "mysticall-main-profile",
["Mstcll-Area 52"] = "Default",
["Mysticallx-Emerald Dream"] = "Default",
["Onlyplaymonk-Sargeras"] = "Default",
["Mysticbankk-Tichondrius"] = "Default",
["Mstcll-Blackwater Raiders"] = "Default",
["Mw-Turalyon"] = "Default",
["Nightmares-Sentinels"] = "DF-Profile",
["Gréëñðrägøñ-Sargeras"] = "Default",
["Rsk-Shandris"] = "Default",
["Craaruun-Eitrigg"] = "Default",
["Flowerlotus-Sentinels"] = "Default",
["Soullstëaler-Sentinels"] = "Default",
["Representing-Blackhand"] = "Default",
["Mediumvibes-Sentinels"] = "Default",
["Lifedestroys-Tichondrius"] = "Default",
["Yungmyst-Sentinels"] = "Default",
["Nerfmw-Moon Guard"] = "Mysticall",
["Cincinatizoo-Sargeras"] = "Default",
["Rsk-Sentinels"] = "Default",
["Mstcll-Garrosh"] = "Default",
["Onlyplaymw-Durotan"] = "Default",
["Thunderbad-Sentinels"] = "DF-Profile",
["Lotusflowers-Sargeras"] = "Default",
["Bovadeez-Bleeding Hollow"] = "Default",
["Weavethemist-Sargeras"] = "DF-Profile",
["Nightbllade-Area 52"] = "Default",
["Yungmyst-Area 52"] = "Default",
["Cocoonjkdead-Bleeding Hollow"] = "Default",
["Mysticbankk-Sentinels"] = "Default",
["Mw-Sargeras"] = "Default",
["Gréëñðrägoñ-Sargeras"] = "mysticall-main-profile",
["Ggs-Detheroc"] = "mysticall-main-profile",
["Soullkeeper-Tichondrius"] = "mysticall-main-profile",
["Sevenseconds-Area 52"] = "Default",
["Hystoricall-Tichondrius"] = "Default",
["Mysticall-Sentinels"] = "Mysticall",
["Mysticbollt-Garrosh"] = "Default",
["Coocoocachu-Sargeras"] = "Default",
["Mstcll-Borean Tundra"] = "Default",
["Nerfmw-Sargeras"] = "Default",
["Enveloping-Area 52"] = "Default",
["Mstcll-Aerie Peak"] = "Default",
["Mstcll-Sentinels"] = "Default",
["Tealcrayon-Anetheron"] = "Default",
["Stylle-Sentinels"] = "Default",
["Mysticallxy-Area 52"] = "Default",
["Onlyplaydru-Sargeras"] = "Default",
["Representing-Area 52"] = "Default",
["Badplat-Sargeras"] = "mysticall-main-profile",
["Cocoonjkdead-Area 52"] = "Mysticall",
["Mysticallx-Tichondrius"] = "Default",
["Sevenseconds-Sargeras"] = "mysticall-main-profile",
["Iamdeadinsid-Sentinels"] = "Default",
["Cocoonjkdead-Sentinels"] = "Mysticall",
["Mwreroll-Sentinels"] = "Default",
["Mysticbollt-Area 52"] = "Default",
["Réðçräñé-Sentinels"] = "Mysticall",
["Hydraxises-Lightning's Blade"] = "Default",
["Mysticbankk-Sargeras"] = "Default",
["Representing-Sargeras"] = "mysticall-main-profile",
["Soullkeeper-Sargeras"] = "DF-Profile",
["Réðçräñé-Sargeras"] = "mysticall-main-profile",
["Weavethemist-Azjol-Nerub"] = "DF-Profile",
["Vezimmarr-Aerie Peak"] = "Default",
["Onlyplaymage-Sargeras"] = "Default",
["Mysticallx-Sargeras"] = "mysticall-main-profile",
["Mysticbankk-Area 52"] = "Default",
["Coccoon-Area 52"] = "Mysticallx-Area 52",
["Mw-Tichondrius"] = "mysticall-main-profile",
["Chithion-Zul'jin"] = "Default",
["Hystoricall-Sentinels"] = "Default",
["Mysticall-Bleeding Hollow"] = "Mysticall",
["Mstcll-Echo Isles"] = "Default",
["Onlyplaypala-Sargeras"] = "Default",
["Mysticall-Moon Guard"] = "Default",
["Onlyplaymonk-Area 52"] = "Default",
["Jayjay-Detheroc"] = "mysticall-main-profile",
["Darkapostle-Tichondrius"] = "Default",
["Thunderbadx-Sargeras"] = "mysticall-main-profile",
["Vivifying-Sentinels"] = "Default",
["Buffmwpls-Sargeras"] = "Default",
["Cocoonjkdead-Aerie Peak"] = "Default",
["Mystweaver-Area 52"] = "Default",
["Enveloping-Sentinels"] = "Default",
["Jje-Vek'nilash"] = "Default",
["Harambad-Sargeras"] = "Default",
["Moosticall-Sentinels"] = "DF-Profile",
["Trialfornowa-Cenarius"] = "Default",
["Vivifying-Area 52"] = "Default",
["Onlyplaydh-Sargeras"] = "Default",
["Lotusflower-Dalvengyr"] = "Default",
["Kickthesun-Sargeras"] = "Default",
["Healjkoom-Sargeras"] = "mysticall-main-profile",
["Zft-Sentinels"] = "Default",
},
["profiles"] = {
["Default"] = {
["categoryTextures"] = {
},
["trackNPCs"] = false,
["announceDRs"] = false,
["timerColors"] = false,
["categoryTextMaxLines"] = 2,
["timerEdge"] = false,
["border"] = {
["layer"] = "BORDER",
["edgeSize"] = 2.5,
["name"] = "Default",
["edgeFile"] = "Interface\\BUTTONS\\UI-Quickslot-Depress",
},
["timerStartAuraEnd"] = false,
["version"] = "1.11",
["timerText"] = true,
["showCategoryText"] = false,
["timerTextOutline"] = "NONE",
["colorBlind"] = false,
["timerSwipe"] = true,
["unitFrames"] = {
["nameplate"] = {
["enabled"] = false,
["iconPadding"] = 7,
["watchFriendly"] = false,
["disabledCategories"] = {
["Taunt"] = true,
["Taunts"] = true,
["Disarms"] = true,
["Disarm"] = true,
},
["zones"] = {
["party"] = false,
["scenario"] = true,
["none"] = true,
["raid"] = false,
["arena"] = true,
["pvp"] = true,
},
["offsetX"] = -33,
["growDirection"] = "RIGHT",
["iconSize"] = 22,
["offsetY"] = 71,
["timerTextSize"] = 12,
["isEnabledForZone"] = false,
},
["player"] = {
["enabled"] = true,
["anchorUIParent"] = false,
["zones"] = {
["party"] = false,
["scenario"] = true,
["none"] = true,
["raid"] = false,
["arena"] = true,
["pvp"] = true,
},
["iconPadding"] = 7,
["watchFriendly"] = true,
["disabledCategories"] = {
["Taunt"] = true,
["Taunts"] = true,
["Disarms"] = true,
["Disarm"] = true,
},
["growDirection"] = "RIGHT",
["offsetX"] = -6,
["timerTextSize"] = 12,
["iconSize"] = 21,
["offsetY"] = 40,
["usePersonalNameplate"] = false,
["isEnabledForZone"] = true,
},
["focus"] = {
["enabled"] = false,
["anchorUIParent"] = false,
["iconPadding"] = 7,
["watchFriendly"] = false,
["disabledCategories"] = {
["Taunt"] = true,
["Taunts"] = true,
["Disarms"] = true,
["Disarm"] = true,
},
["zones"] = {
["party"] = false,
["scenario"] = true,
["none"] = true,
["raid"] = false,
["arena"] = false,
["pvp"] = true,
},
["offsetX"] = 104,
["growDirection"] = "RIGHT",
["iconSize"] = 22,
["offsetY"] = 23,
["timerTextSize"] = 12,
["isEnabledForZone"] = false,
},
["target"] = {
["enabled"] = false,
["anchorUIParent"] = false,
["iconPadding"] = 7,
["watchFriendly"] = false,
["disabledCategories"] = {
["Taunt"] = true,
["Taunts"] = true,
["Disarms"] = true,
["Disarm"] = true,
},
["zones"] = {
["party"] = false,
["scenario"] = true,
["none"] = true,
["raid"] = false,
["arena"] = false,
["pvp"] = true,
},
["offsetX"] = 104,
["growDirection"] = "RIGHT",
["iconSize"] = 22,
["offsetY"] = 23,
["timerTextSize"] = 12,
["isEnabledForZone"] = false,
},
["arena"] = {
["enabled"] = false,
["anchorUIParent"] = false,
["iconPadding"] = 7,
["disabledCategories"] = {
["Taunt"] = true,
["Taunts"] = true,
["Disarms"] = true,
["Disarm"] = true,
},
["zones"] = {
["party"] = false,
["scenario"] = false,
["none"] = false,
["raid"] = false,
["arena"] = true,
["pvp"] = false,
},
["offsetX"] = -66,
["growDirection"] = "LEFT",
["iconSize"] = 22,
["offsetY"] = 20,
["timerTextSize"] = 12,
["isEnabledForZone"] = false,
},
["party"] = {
["enabled"] = true,
["anchorUIParent"] = false,
["iconPadding"] = 6,
["watchFriendly"] = true,
["disabledCategories"] = {
["Taunt"] = true,
["Taunts"] = true,
["Disarms"] = true,
["Disarm"] = true,
},
["zones"] = {
["party"] = false,
["scenario"] = false,
["none"] = true,
["raid"] = false,
["arena"] = true,
["pvp"] = false,
},
["offsetX"] = 76,
["growDirection"] = "RIGHT",
["iconSize"] = 24,
["offsetY"] = 7,
["timerTextSize"] = 12,
["isEnabledForZone"] = true,
},
},
["categoryFont"] = {
["x"] = 0,
["size"] = 9,
},
},
["mysticall-main-profile"] = {
["categoryTextures"] = {
},
["timerColors"] = false,
["timerEdge"] = false,
["trackNPCs"] = false,
["announceDRs"] = false,
["timerStartAuraEnd"] = false,
["border"] = {
["layer"] = "OVERLAY",
["edgeSize"] = 1,
["name"] = "Default, with glow",
["edgeFile"] = "Interface\\BUTTONS\\UI-Quickslot-Depress",
},
["categoryTextMaxLines"] = 2,
["version"] = "1.11",
["timerSwipe"] = false,
["showCategoryText"] = false,
["timerTextOutline"] = "THICKOUTLINE",
["colorBlind"] = false,
["timerText"] = true,
["unitFrames"] = {
["nameplate"] = {
["enabled"] = true,
["iconPadding"] = 2,
["watchFriendly"] = false,
["disabledCategories"] = {
["Disarms"] = false,
["Taunts"] = true,
["Roots"] = true,
["Taunt"] = true,
["Disarm"] = true,
},
["zones"] = {
["party"] = false,
["scenario"] = true,
["pvp"] = true,
["raid"] = false,
["arena"] = true,
["none"] = true,
},
["offsetX"] = 73,
["timerTextSize"] = 7,
["iconSize"] = 22,
["offsetY"] = 1,
["growDirection"] = "RIGHT",
["isEnabledForZone"] = true,
},
["player"] = {
["zones"] = {
["party"] = false,
["scenario"] = true,
["pvp"] = true,
["raid"] = false,
["arena"] = true,
["none"] = true,
},
["anchorUIParent"] = true,
["offsetsY"] = {
-184,
},
["enabled"] = true,
["offsetsX"] = {
-304,
},
["iconPadding"] = 1,
["watchFriendly"] = true,
["disabledCategories"] = {
["Disarms"] = true,
["Disorients"] = false,
["Knockbacks"] = true,
["Disarm"] = true,
["Roots"] = true,
["Taunt"] = true,
["Taunts"] = true,
},
["timerTextSize"] = 15,
["offsetX"] = -6,
["growDirection"] = "RIGHT",
["iconSize"] = 45,
["offsetY"] = 40,
["usePersonalNameplate"] = false,
["isEnabledForZone"] = true,
},
["focus"] = {
["enabled"] = false,
["anchorUIParent"] = false,
["iconPadding"] = 7,
["watchFriendly"] = false,
["disabledCategories"] = {
["Taunts"] = true,
["Disarm"] = true,
["Disarms"] = true,
["Taunt"] = true,
},
["zones"] = {
["party"] = false,
["scenario"] = true,
["pvp"] = true,
["raid"] = false,
["arena"] = false,
["none"] = true,
},
["offsetX"] = 104,
["timerTextSize"] = 12,
["iconSize"] = 22,
["offsetY"] = 23,
["growDirection"] = "RIGHT",
["isEnabledForZone"] = false,
},
["target"] = {
["enabled"] = false,
["anchorUIParent"] = false,
["iconPadding"] = 7,
["watchFriendly"] = false,
["disabledCategories"] = {
["Taunts"] = true,
["Disarm"] = true,
["Disarms"] = true,
["Taunt"] = true,
},
["zones"] = {
["party"] = false,
["scenario"] = true,
["pvp"] = true,
["raid"] = false,
["arena"] = false,
["none"] = true,
},
["offsetX"] = 104,
["timerTextSize"] = 12,
["iconSize"] = 22,
["offsetY"] = 23,
["growDirection"] = "RIGHT",
["isEnabledForZone"] = false,
},
["arena"] = {
["enabled"] = true,
["anchorUIParent"] = false,
["offsetsY"] = {
20,
20,
20,
20,
20,
},
["iconPadding"] = 4,
["offsetsX"] = {
0,
0,
0,
0,
0,
},
["disabledCategories"] = {
["Taunt"] = true,
["Disarms"] = false,
["Disarm"] = true,
["Roots"] = false,
["Taunts"] = true,
["Silences"] = false,
},
["timerTextSize"] = 10,
["offsetX"] = -68,
["growDirection"] = "LEFT",
["iconSize"] = 21,
["offsetY"] = 24,
["zones"] = {
["party"] = false,
["scenario"] = false,
["pvp"] = false,
["raid"] = false,
["arena"] = true,
["none"] = false,
},
["isEnabledForZone"] = false,
},
["party"] = {
["enabled"] = false,
["anchorUIParent"] = true,
["offsetsY"] = {
-101,
-29,
113,
115,
12,
},
["zones"] = {
["party"] = false,
["scenario"] = false,
["pvp"] = false,
["raid"] = false,
["arena"] = true,
["none"] = true,
},
["iconPadding"] = 0,
["watchFriendly"] = true,
["disabledCategories"] = {
["Taunt"] = true,
["Knockbacks"] = true,
["Disarm"] = true,
["Roots"] = true,
["Taunts"] = true,
["Disarms"] = true,
},
["offsetsX"] = {
-341,
-339,
-369,
-303,
0,
},
["offsetX"] = 191,
["timerTextSize"] = 12,
["iconSize"] = 21,
["offsetY"] = 12,
["growDirection"] = "LEFT",
["isEnabledForZone"] = false,
},
},
["categoryFont"] = {
["x"] = 0,
["size"] = 9,
},
},
},
}
