
EasyFramesDB = {
["profileKeys"] = {
["Hystoricall - Tichondrius"] = "Default",
["Justinjames - Sentinels"] = "Default",
["Mstcll - Borean Tundra"] = "Default",
["Mstcll - Garrosh"] = "Default",
["Onlyplaypala - Sargeras"] = "Default",
["Yungmyst - Area 52"] = "Default",
["Lotusflower - Dalvengyr"] = "Default",
["Réðçräñé - Sargeras"] = "Default",
["Mstcll - Sargeras"] = "Default",
["Badplat - Sargeras"] = "Default",
["Lotusflowers - Sargeras"] = "Default",
["Nerfmw - Moon Guard"] = "Default",
["Vivifying - Sentinels"] = "Default",
["Mysticallx - Tichondrius"] = "Default",
["Flowerlotus - Sentinels"] = "Default",
["Mw - Tichondrius"] = "mysticall-main-profile",
["Mystweaver - Area 52"] = "Default",
["Cocoonjkdead - Sentinels"] = "Default",
["Chithion - Zul'jin"] = "Default",
["Harambad - Sargeras"] = "Default",
["Onlyplaydh - Sargeras"] = "Default",
["Gréëñðrägoñ - Sargeras"] = "Default",
["Trialfornowa - Cenarius"] = "Default",
["Yungmyst - Sentinels"] = "Default",
["Justinjames - Area 52"] = "Default",
["Mysticbankk - Area 52"] = "Default",
["Hystoricall - Sentinels"] = "Default",
["Enveloping - Area 52"] = "Default",
["Justinjames - Sargeras"] = "Default",
["Mysticallxd - Sargeras"] = "Default",
["Darkapostle - Tichondrius"] = "Default",
["Coocoocachu - Sargeras"] = "Default",
["Jayjay - Detheroc"] = "mysticall-main-profile",
["Mwreroll - Sentinels"] = "Default",
["Mediumvibes - Area 52"] = "Default",
["Zft - Sentinels"] = "Default",
["Buffmwpls - Sargeras"] = "Default",
["Onlyplaymonk - Sargeras"] = "Default",
["Yungmyst - Sargeras"] = "Default",
["Cocoonjkdead - Bleeding Hollow"] = "Default",
["Onlyplayfury - Sargeras"] = "Default",
["Rsk - Shandris"] = "Default",
["Onlyplaymw - Durotan"] = "Default",
["Zft - Area 52"] = "Default",
["Mysticall - Moon Guard"] = "Default",
["Fixmwplease - Area 52"] = "Default",
["Ashdfh - Mythic Dungeon Heroes - US"] = "Default",
["Moosticall - Sentinels"] = "Default",
["Tealcrayon - Anetheron"] = "Default",
["Mysticbankk - Sargeras"] = "Default",
["Soullstëaler - Sentinels"] = "Default",
["Soullkeeper - Tichondrius"] = "mysticall-main-profile",
["Mysticbankk - Sentinels"] = "Default",
["Mw - Turalyon"] = "Default",
["Mysticbankk - Tichondrius"] = "Default",
["Representing - Area 52"] = "Default",
["Healjkoom - Sargeras"] = "mysticall-main-profile",
["Mstcll - Aerie Peak"] = "Default",
["Sevenseconds - Area 52"] = "Default",
["Sevenseconds - Sargeras"] = "mysticall-main-profile",
["Coccoon - Area 52"] = "Default",
["Kickthesun - Sargeras"] = "Default",
["Iamdeadinsid - Sentinels"] = "Default",
["Thunderbadx - Sargeras"] = "Default",
["Stylle - Sentinels"] = "Default",
["Onlyplaymonk - Area 52"] = "Default",
["Mwreroll - Sargeras"] = "Default",
["Craaruun - Eitrigg"] = "Default",
["Cocoonjkdead - Aerie Peak"] = "Default",
["Mediumvibes - Sentinels"] = "Default",
["Mstcll - Blackwater Raiders"] = "Default",
["Mstcll - Sentinels"] = "Default",
["Cincinatizoo - Sargeras"] = "Default",
["Mysticbollt - Garrosh"] = "Default",
["Lifedestroys - Tichondrius"] = "Default",
["Mstcll - Area 52"] = "Default",
["Mysticallxy - Area 52"] = "Default",
["Mstcll - Echo Isles"] = "Default",
["Rsk - Sentinels"] = "Default",
["Onlyplaydru - Sargeras"] = "Default",
["Hydraxises - Lightning's Blade"] = "Default",
["Mysticallx - Sargeras"] = "mysticall-main-profile",
["Representing - Blackhand"] = "Default",
["Thunderbad - Sentinels"] = "Default",
["Representing - Sargeras"] = "Default",
["Onlyplaysub - Sargeras"] = "Default",
["Vivifying - Area 52"] = "Default",
["Gréëñðrägøñ - Sargeras"] = "Default",
["Onlyplaymage - Sargeras"] = "Default",
["Nerfmw - Sargeras"] = "Default",
["Ggs - Detheroc"] = "mysticall-main-profile",
["Misstickle - Sargeras"] = "Default",
["Nightbllade - Area 52"] = "Default",
["Jje - Vek'nilash"] = "Default",
["Vezimmarr - Aerie Peak"] = "Default",
["Enveloping - Sentinels"] = "Default",
},
["profiles"] = {
["Mysticallx - Sargeras"] = {
},
["Default"] = {
["target"] = {
["healthFormat"] = "2",
},
["player"] = {
["healthFormat"] = "2",
["showPVPIcon"] = false,
["healthBarFontStyle"] = "THICKOUTLINE",
},
["general"] = {
["showOnlyMyDebuff"] = true,
["maxDebuffCount"] = 10,
["selfBuffSize"] = 19,
["barTexture"] = "Default",
["buffSize"] = 19,
["maxBuffCount"] = 14,
},
["focus"] = {
["showPVPIcon"] = false,
["showName"] = false,
},
},
["mysticall-main-profile"] = {
["player"] = {
["attackBackgroundOpacity"] = 0.684210479259491,
["scaleFrame"] = 1.199579358100891,
["healthFormat"] = "1",
["showHitIndicator"] = false,
},
["general"] = {
["maxBuffCount"] = 10,
["buffSize"] = 20,
["highlightDispelledBuff"] = false,
["showWelcomeMessage"] = false,
["hideOutOfCombatOpacity"] = 0,
["selfBuffSize"] = 20,
["barTexture"] = "Smooth",
["brightFrameBorder"] = 0,
},
["focus"] = {
["manaFormat"] = "1",
["showToTFrame"] = false,
["showAttackBackground"] = false,
["showPVPIcon"] = false,
["healthFormat"] = "1",
["showName"] = false,
["attackBackgroundOpacity"] = 0.7236872315406799,
},
["target"] = {
["targetNameFontFamily"] = "2002 Bold",
["showPVPIcon"] = false,
["attackBackgroundOpacity"] = 0.7039502263069153,
["healthFormat"] = "1",
},
["pet"] = {
["healthFormat"] = "1",
},
},
["MONK"] = {
},
["Sargeras"] = {
},
},
}
