
FriendGroups_SavedVars = {
["hide_high_level"] = true,
["hide_offline"] = false,
["add_mobile_text"] = true,
["show_btag"] = false,
["auto_accept_invite"] = false,
["colour_classes"] = true,
["collapsed"] = {
["goodWarlock"] = false,
["mainpartners"] = false,
["dk"] = false,
["WW"] = false,
["alt-Ele-DH"] = false,
["2s"] = false,
["Ele"] = false,
["[No Group]"] = false,
["warrior"] = false,
["restoDruid"] = false,
["rbgs"] = false,
["twitchfriends"] = false,
["shadowplay priest"] = false,
["pve"] = false,
["ARealOne"] = false,
["mw"] = false,
["shadowplay demo lock"] = false,
["HS"] = false,
["pve "] = false,
["outlaw"] = false,
},
["show_faction_icons"] = true,
}
