
REPorterSettings = {
["profileKeys"] = {
["Cocoonjkdead - Aerie Peak"] = "Default",
["Justinjames - Sentinels"] = "Default",
["Mstcll - Borean Tundra"] = "Default",
["Mstcll - Garrosh"] = "Default",
["Onlyplaymage - Sargeras"] = "Default",
["Lotusflower - Dalvengyr"] = "Default",
["Réðçräñé - Sargeras"] = "Default",
["Holÿ - Lightning's Blade"] = "Default",
["Magycall - Emerald Dream"] = "Default",
["Lotusflowers - Sargeras"] = "Default",
["Nerfmw - Moon Guard"] = "Default",
["Vivifying - Sentinels"] = "Default",
["Mysticallx - Tichondrius"] = "Default",
["Flowerlotus - Sentinels"] = "Default",
["Mw - Tichondrius"] = "Default",
["Enveloping - Sentinels"] = "Default",
["Badplat - Sargeras"] = "Default",
["Cocoonjkdead - Sentinels"] = "Default",
["Vezimmarr - Aerie Peak"] = "Default",
["Mysticall - Bleeding Hollow"] = "Default",
["Harambad - Sargeras"] = "Default",
["Onlyplaydh - Sargeras"] = "Default",
["Gréëñðrägoñ - Sargeras"] = "Default",
["Representing - Sargeras"] = "Default",
["Fanarassa - Sentinels"] = "Default",
["Yungmyst - Sentinels"] = "Default",
["Gréëñðrägøñ - Sargeras"] = "Default",
["Mysticbankk - Area 52"] = "Default",
["Mysticall - Moon Guard"] = "Default",
["Anonymage - Blackhand"] = "Default",
["Soullkeeper - Tichondrius"] = "Default",
["Nerfmw - Sargeras"] = "Default",
["Kickthesun - Sargeras"] = "Default",
["Mysticall - Sentinels"] = "Default",
["Alunadris - Sentinels"] = "Default",
["Coocoocachu - Sargeras"] = "Default",
["Jayjay - Detheroc"] = "Default",
["Mwreroll - Sentinels"] = "Default",
["Jje - Vek'nilash"] = "Default",
["Onlyplaymw - Durotan"] = "Default",
["Soullkeeper - Sargeras"] = "Default",
["Baotu - Sargeras"] = "Default",
["Representing - Area 52"] = "Default",
["Mediumvibes - Area 52"] = "Default",
["Hystoricall - Sentinels"] = "Default",
["Sydarelora - Draenor"] = "Default",
["Mysticbankk - Sentinels"] = "Default",
["Thunderbad - Sentinels"] = "Default",
["Buffmwpls - Sargeras"] = "Default",
["Soullstëaler - Sentinels"] = "Default",
["Réðçräñé - Sentinels"] = "Default",
["Mysticallx - Sargeras"] = "Default",
["Hydraxises - Lightning's Blade"] = "Default",
["Cocoonjkdead - Bleeding Hollow"] = "Default",
["Andrista - Bloodhoof"] = "Default",
["Wymoralt - Proudmoore"] = "Default",
["Mysticallx - Area 52"] = "Default",
["Mw - Turalyon"] = "Default",
["Zft - Area 52"] = "Default",
["Mstcll - Echo Isles"] = "Default",
["Mysticallxy - Area 52"] = "Default",
["Curtimer - Emerald Dream"] = "Default",
["Mediumvibes - Sentinels"] = "Default",
["Tealcrayon - Anetheron"] = "Default",
["Mysticbankk - Sargeras"] = "Default",
["Moosticall - Sentinels"] = "Default",
["Mysticbankk - Garrosh"] = "Default",
["Mw - Sargeras"] = "Default",
["Azshauleand - Sargeras"] = "Default",
["Iamdeadinsid - Sentinels"] = "Default",
["Stylle - Sentinels"] = "Default",
["Healjkoom - Sargeras"] = "Default",
["Mstcll - Aerie Peak"] = "Default",
["Sevenseconds - Area 52"] = "Default",
["Mysticall - Borean Tundra"] = "Default",
["Elamatrenn - Emerald Dream"] = "Default",
["Cincinatizoo - Sargeras"] = "Default",
["Bovadeez - Bleeding Hollow"] = "Default",
["Thunderbadx - Sargeras"] = "Default",
["Mstcll - Sentinels"] = "Default",
["Onlyplaydru - Sargeras"] = "Default",
["Onlyplaymonk - Area 52"] = "Default",
["Craaruun - Eitrigg"] = "Default",
["Sadfeesaddsf - Nemesis"] = "Default",
["Hydraxis - Lightning's Blade"] = "Default",
["Mstcll - Blackwater Raiders"] = "Default",
["Weavethemist - Sargeras"] = "Default",
["Nightmares - Sentinels"] = "Default",
["Mysticbollt - Garrosh"] = "Default",
["Gracefulness - Sargeras"] = "Default",
["Mstcll - Area 52"] = "Default",
["Mysticbollt - Area 52"] = "Default",
["Lifedestroys - Tichondrius"] = "Default",
["Green - Eitrigg"] = "Default",
["Mysticbankk - Tichondrius"] = "Default",
["Rsk - Sentinels"] = "Default",
["Mysticallx - Emerald Dream"] = "Default",
["Representing - Blackhand"] = "Default",
["Hydraxicle - Lightning's Blade"] = "Default",
["Coccoon - Area 52"] = "Default",
["Rsk - Shandris"] = "Default",
["Zft - Sentinels"] = "Default",
["Soullstëaler - Blackhand"] = "Default",
["Ruchi - Sentinels"] = "Default",
["Yungmyst - Area 52"] = "Default",
["Ggs - Detheroc"] = "Default",
["Sevenseconds - Sargeras"] = "Default",
["Nightbllade - Area 52"] = "Default",
["Mwreroll - Sargeras"] = "Default",
["Mysticallud - Arena Champions - US"] = "Default",
["Cocoonjkdead - Area 52"] = "Default",
},
["profiles"] = {
["Default"] = {
["Map"] = {
[275] = {
["ms"] = 1.15,
["wy"] = 482,
["wx"] = 1826,
},
[206] = {
["wy"] = 449,
["wx"] = 1769,
},
[169] = {
["wy"] = 531,
["wx"] = 1775,
},
[623] = {
["wy"] = 420,
["wx"] = 1721,
},
[907] = {
["my"] = -113,
["ww"] = 328,
["wh"] = 285,
["ms"] = 0.7,
["mx"] = 82,
["wy"] = 411,
["wx"] = 179,
},
[423] = {
["my"] = -75,
["ww"] = 370,
["wh"] = 285,
["ms"] = 0.7,
["mx"] = 53,
["wy"] = 470,
["wx"] = 1855,
},
[112] = {
["my"] = -24,
["ww"] = 230,
["wh"] = 394,
["ms"] = 1.05,
["mx"] = 18,
["wy"] = 502,
["wx"] = 1757,
},
[417] = {
["ms"] = 0.7,
["ww"] = 328,
["wh"] = 249,
["mx"] = 50,
["wy"] = 457,
["wx"] = 1808,
},
[2345] = {
["ms"] = 0.7,
["wy"] = 469,
["wx"] = 1789,
},
[91] = {
["my"] = -32,
["ww"] = 191,
["wh"] = 439,
["ms"] = 0.85,
["mx"] = 16,
["wy"] = 529,
["wx"] = 1469,
},
[1334] = {
["ms"] = 0.8,
["wy"] = 335,
["wx"] = 1634,
},
[1366] = {
["ms"] = 0.95,
["wy"] = 441,
["wx"] = 1858,
},
[1335] = {
["wx"] = 683,
},
[1339] = {
["ms"] = 1.2,
["wy"] = 490,
["wx"] = 1797,
},
[1478] = {
["wy"] = 165,
["wx"] = 1785,
},
[1576] = {
["my"] = -78,
["ww"] = 425,
["wh"] = 383,
["ms"] = 0.95,
["mx"] = 50,
["wy"] = 501,
["wx"] = 1854,
},
},
["BarY"] = 459.9999389648438,
["BarX"] = 1915.5,
["Opacity"] = 1,
["DisplayMarks"] = true,
},
},
}
