
sArena3DB = {
["profileKeys"] = {
["Hystoricall - Tichondrius"] = "Default",
["Justinjames - Sentinels"] = "Default",
["Mstcll - Borean Tundra"] = "Default",
["Mstcll - Garrosh"] = "Default",
["Onlyplaypala - Sargeras"] = "Default",
["Onlyplaymage - Sargeras"] = "Default",
["Lotusflower - Dalvengyr"] = "Default",
["Réðçräñé - Sargeras"] = "mysticall-main-tww",
["Representing - Area 52"] = "Default",
["Magycall - Emerald Dream"] = "mysticall-main-tww",
["Lotusflowers - Sargeras"] = "Default",
["Vivifying - Sentinels"] = "Default",
["Mysticallx - Tichondrius"] = "Default",
["Flowerlotus - Sentinels"] = "Default",
["Mw - Tichondrius"] = "mysticall-main-tww",
["Hordebanker - Sargeras"] = "Default",
["Mystweaver - Area 52"] = "Default",
["Vezimmarr - Aerie Peak"] = "Default",
["Onlyplaydh - Sargeras"] = "mysticall-main-tww",
["Onlyplaymw - Durotan"] = "Default",
["Trialfornowa - Cenarius"] = "Default",
["Yungmyst - Sentinels"] = "Default",
["Gréëñðrägøñ - Sargeras"] = "Default",
["Mysticbankk - Area 52"] = "Default",
["Mysticall - Moon Guard"] = "Default",
["Enveloping - Area 52"] = "Default",
["Jje - Vek'nilash"] = "Default",
["Mysticallxd - Sargeras"] = "Default",
["Vivifying - Area 52"] = "Default",
["Mwreroll - Sentinels"] = "Default",
["Badplat - Sargeras"] = "mysticall-main-tww",
["Zft - Sentinels"] = "Default",
["Fanarassa - Sentinels"] = "Default",
["Alunadris - Sentinels"] = "Default",
["Mysticallud - Arena Champions - US"] = "Default",
["Soullkeeper - Tichondrius"] = "mysticall-main-tww",
["Onlyplaymonk - Sargeras"] = "Default",
["Hystoricall - Sentinels"] = "Default",
["Yungmyst - Sargeras"] = "Default",
["Cocoonjkdead - Bleeding Hollow"] = "Default",
["Andrista - Bloodhoof"] = "Default",
["Mstcll - Sargeras"] = "Default",
["Rsk - Shandris"] = "mysticall-main-tww",
["Chithion - Zul'jin"] = "Default",
["Zft - Area 52"] = "Default",
["Representing - Sargeras"] = "mysticall-main-tww",
["Mstcll - Blackhand"] = "mysticall-main-tww",
["Ashdfh - Mythic Dungeon Heroes - US"] = "Default",
["Mysticbankk - Tichondrius"] = "Default",
["Tealcrayon - Anetheron"] = "Default",
["Mysticbankk - Sargeras"] = "Default",
["Soullstëaler - Sentinels"] = "Default",
["Mysticbankk - Garrosh"] = "Default",
["Mysticbankk - Sentinels"] = "Default",
["Azshauleand - Sargeras"] = "Default",
["Iamdeadinsid - Sentinels"] = "Default",
["Curtimer - Emerald Dream"] = "Default",
["Green - Eitrigg"] = "mysticall-main-tww",
["Mstcll - Aerie Peak"] = "Default",
["Sevenseconds - Area 52"] = "Default",
["Gréëñðrägoñ - Sargeras"] = "mysticall-main-tww",
["Elamatrenn - Emerald Dream"] = "Default",
["Hydraxicle - Lightning's Blade"] = "Default",
["Coocoocachu - Sargeras"] = "Default",
["Thunderbadx - Sargeras"] = "mysticall-main-tww",
["Mstcll - Sentinels"] = "Default",
["Onlyplaymonk - Area 52"] = "Default",
["Onlyplaydru - Sargeras"] = "Default",
["Craaruun - Eitrigg"] = "Default",
["Sadfeesaddsf - Nemesis"] = "Default",
["Mw - Turalyon"] = "Default",
["Mstcll - Blackwater Raiders"] = "Default",
["Mediumvibes - Sentinels"] = "Default",
["Stylle - Sentinels"] = "Default",
["Mysticbollt - Garrosh"] = "Default",
["Gracefulness - Sargeras"] = "mysticall-main-tww",
["Mstcll - Area 52"] = "Default",
["Mysticbollt - Area 52"] = "Default",
["Mstcll - Echo Isles"] = "Default",
["Lifedestroys - Tichondrius"] = "mysticall-main-tww",
["Mw - Sargeras"] = "Default",
["Hydraxises - Lightning's Blade"] = "Default",
["Mysticallx - Sargeras"] = "mysticall-main-tww",
["Nerfmw - Sargeras"] = "mysticall-main-tww",
["Thunderbad - Sentinels"] = "mysticall-main-tww",
["Yungmyst - Area 52"] = "Default",
["Onlyplaysub - Sargeras"] = "Default",
["Wymoralt - Proudmoore"] = "Default",
["Baotu - Sargeras"] = "mysticall-main-tww",
["Ruchi - Sentinels"] = "Default",
["Justinjames - Sargeras"] = "Default",
["Ggs - Detheroc"] = "mysticall-main-tww",
["Misstickle - Sargeras"] = "Default",
["Nightbllade - Area 52"] = "Default",
["Cocoonjkdead - Aerie Peak"] = "Default",
["Sydarelora - Draenor"] = "Default",
["Onlyplayfury - Sargeras"] = "Default",
},
["profiles"] = {
["Default"] = {
["layoutSettings"] = {
["BlizzArena"] = {
["scale"] = 1.8,
["posY"] = 5.5,
["posX"] = 205.2,
},
},
["statusText"] = {
["usePercentage"] = true,
},
["drCategories"] = {
["Incapacitate"] = false,
["Root"] = false,
["Disorient"] = false,
["Stun"] = false,
["Silence"] = false,
},
},
["mysticall-main-tww"] = {
["layoutSettings"] = {
["Xaryu"] = {
["spacing"] = 48,
["posY"] = 30,
["castBar"] = {
["posX"] = -61,
["scale"] = 1.5,
},
["posX"] = 294,
},
["Blizz Modern"] = {
["dr"] = {
["posX"] = -200,
["posY"] = 30,
["size"] = 36,
},
["posY"] = -10.8,
["scale"] = 0.9,
["specIcon"] = {
["scale"] = 1.2,
["posY"] = -19,
["posX"] = 77,
},
["castBar"] = {
["scale"] = 1.8,
["posX"] = -142,
["posY"] = 1,
["width"] = 84,
},
["classIconFontSize"] = 19,
["posX"] = 409.8,
["trinket"] = {
["scale"] = 1.4,
["posY"] = -2,
["posX"] = -84,
},
["racial"] = {
["scale"] = 1.4,
["posY"] = -2,
["posX"] = -113,
},
},
["BlizzArena"] = {
["dr"] = {
["size"] = 19,
},
["scale"] = 1.6,
["specIcon"] = {
["posY"] = -13,
["posX"] = 48,
},
["posX"] = 231.9,
["posY"] = -27.4,
["trinket"] = {
["posY"] = 0,
},
},
},
["currentLayout"] = "BlizzTourney",
["statusText"] = {
["usePercentage"] = true,
},
["drDynamicIcons"] = true,
["racialCategories"] = {
["Dracthyr"] = false,
["HighmountainTauren"] = false,
["Orc"] = false,
["Troll"] = false,
["Earthen"] = false,
["Mechagnome"] = false,
["Vulpera"] = false,
["ZandalariTroll"] = false,
["Worgen"] = false,
["BloodElf"] = false,
["Nightborne"] = false,
["MagharOrc"] = false,
["LightforgedDraenei"] = false,
["Goblin"] = false,
},
["drCategories"] = {
["Root"] = false,
},
},
},
}
