
sArena3DB = {
["profileKeys"] = {
["Hystoricall - Tichondrius"] = "Default",
["Justinjames - Sentinels"] = "Default",
["Mstcll - Borean Tundra"] = "Default",
["Mstcll - Garrosh"] = "Default",
["Onlyplaypala - Sargeras"] = "Default",
["Onlyplaymage - Sargeras"] = "Default",
["Lotusflower - Dalvengyr"] = "Default",
["Réðçräñé - Sargeras"] = "df-profile",
["Mstcll - Sargeras"] = "df-profile",
["Badplat - Sargeras"] = "df-profile",
["Lotusflowers - Sargeras"] = "Default",
["Nerfmw - Moon Guard"] = "Mysticall",
["Vivifying - Sentinels"] = "Default",
["Mysticallx - Tichondrius"] = "Default",
["Flowerlotus - Sentinels"] = "Default",
["Mw - Tichondrius"] = "df-profile",
["Hordebanker - Sargeras"] = "Default",
["Onlyplayfury - Sargeras"] = "Default",
["Mystweaver - Area 52"] = "Default",
["Magycall - Emerald Dream"] = "df-profile",
["Cocoonjkdead - Sentinels"] = "Main-Profile",
["Vezimmarr - Aerie Peak"] = "Default",
["Mysticall - Bleeding Hollow"] = "Mysticall",
["Harambad - Sargeras"] = "df-profile",
["Onlyplaydh - Sargeras"] = "Mysticall",
["Gréëñðrägoñ - Sargeras"] = "df-profile",
["Representing - Sargeras"] = "df-profile",
["Onlyplaymw - Durotan"] = "Default",
["Yungmyst - Sentinels"] = "Default",
["Gréëñðrägøñ - Sargeras"] = "Default",
["Mysticbankk - Area 52"] = "Default",
["Mysticall - Moon Guard"] = "Default",
["Nightbllade - Area 52"] = "Default",
["Enveloping - Area 52"] = "Default",
["Justinjames - Sargeras"] = "Default",
["Mysticallxd - Sargeras"] = "Default",
["Hystoricall - Sentinels"] = "Default",
["Darkapostle - Tichondrius"] = "df-profile",
["Vivifying - Area 52"] = "Default",
["Jayjay - Detheroc"] = "df-profile",
["Mwreroll - Sentinels"] = "Default",
["Soullkeeper - Tichondrius"] = "df-profile",
["Cocoonjkdead - Area 52"] = "Mysticall",
["Mwreroll - Sargeras"] = "df-profile",
["Representing - Area 52"] = "Default",
["Soullkeeper - Sargeras"] = "df-profile",
["Kickthesun - Sargeras"] = "df-profile",
["Coocoocachu - Sargeras"] = "Default",
["Zft - Sentinels"] = "Default",
["Hydraxicle - Lightning's Blade"] = "Default",
["Onlyplaymonk - Sargeras"] = "Default",
["Buffmwpls - Sargeras"] = "df-profile",
["Mysticallx - Emerald Dream"] = "df-profile",
["Réðçräñé - Sentinels"] = "df-profile",
["Hydraxises - Lightning's Blade"] = "Default",
["Yungmyst - Sargeras"] = "Default",
["Cocoonjkdead - Bleeding Hollow"] = "Default",
["Rsk - Shandris"] = "Default",
["Mysticbankk - Sentinels"] = "Default",
["Mysticallx - Area 52"] = "Mysticall",
["Mstcll - Echo Isles"] = "Default",
["Zft - Area 52"] = "Default",
["Mysticbollt - Area 52"] = "Main-Profile",
["Mstcll - Blackhand"] = "Default",
["Ashdfh - Mythic Dungeon Heroes - US"] = "Default",
["Mw - Turalyon"] = "Default",
["Tealcrayon - Anetheron"] = "Default",
["Mysticbankk - Sargeras"] = "Default",
["Moosticall - Sentinels"] = "df-profile",
["Mysticbankk - Garrosh"] = "Default",
["Mw - Sargeras"] = "Default",
["Healjkoom - Sargeras"] = "df-profile",
["Mysticbankk - Tichondrius"] = "Default",
["Mediumvibes - Sentinels"] = "Default",
["Green - Eitrigg"] = "MONK",
["Mstcll - Aerie Peak"] = "Default",
["Sevenseconds - Area 52"] = "Default",
["Nightmares - Sentinels"] = "df-profile",
["Elamatrenn - Emerald Dream"] = "Default",
["Mstcll - Sentinels"] = "Default",
["Bovadeez - Bleeding Hollow"] = "Mysticall",
["Thunderbadx - Sargeras"] = "df-profile",
["Stylle - Sentinels"] = "Default",
["Onlyplaymonk - Area 52"] = "Default",
["Onlyplaydru - Sargeras"] = "Default",
["Craaruun - Eitrigg"] = "Default",
["Weavethemist - Sargeras"] = "df-profile",
["Cocoonjkdead - Aerie Peak"] = "Default",
["Mstcll - Blackwater Raiders"] = "Default",
["Yungmyst - Area 52"] = "Default",
["Cincinatizoo - Sargeras"] = "Mysticall",
["Mysticbollt - Garrosh"] = "Default",
["Curtimer - Emerald Dream"] = "Default",
["Mstcll - Area 52"] = "Default",
["Mysticallxy - Area 52"] = "Main-Profile",
["Lifedestroys - Tichondrius"] = "Default",
["Soullstëaler - Sentinels"] = "Default",
["Iamdeadinsid - Sentinels"] = "Default",
["Rsk - Sentinels"] = "df-profile",
["Mysticallx - Sargeras"] = "mysticall-main-tww",
["Representing - Blackhand"] = "Mysticall",
["Thunderbad - Sentinels"] = "df-profile",
["Chithion - Zul'jin"] = "Default",
["Onlyplaysub - Sargeras"] = "Default",
["Weavethemist - Azjol-Nerub"] = "df-profile",
["Baotu - Sargeras"] = "Default",
["Sevenseconds - Sargeras"] = "df-profile",
["Nerfmw - Sargeras"] = "Default",
["Ggs - Detheroc"] = "df-profile",
["Misstickle - Sargeras"] = "Default",
["Mysticall - Sentinels"] = "df-profile",
["Jje - Vek'nilash"] = "Default",
["Trialfornowa - Cenarius"] = "Default",
["Enveloping - Sentinels"] = "Main-Profile",
},
["profiles"] = {
["Mysticall"] = {
["layoutSettings"] = {
["BlizzArena"] = {
["dr"] = {
["size"] = 19,
},
["posY"] = -25.3,
["posX"] = 219.3,
["scale"] = 1.6,
["trinket"] = {
["posY"] = 0,
},
},
["Xaryu"] = {
["castBar"] = {
["scale"] = 1.5,
["posX"] = -61,
},
["posX"] = 294,
["posY"] = 30,
["spacing"] = 48,
},
},
["currentLayout"] = "Blizz Modern",
["statusText"] = {
["usePercentage"] = true,
},
["drCategories"] = {
["Incapacitate"] = false,
["Root"] = false,
["Disorient"] = false,
["Stun"] = false,
["Silence"] = false,
},
["drDynamicIcons"] = true,
},
["Main-Profile"] = {
["layoutSettings"] = {
["BlizzArena"] = {
["dr"] = {
["size"] = 19,
},
["posY"] = -7.1,
["posX"] = 226.2,
["scale"] = 1.6,
["trinket"] = {
["posY"] = 0,
},
},
["Xaryu"] = {
["castBar"] = {
["scale"] = 1.5,
["posX"] = -61,
},
["spacing"] = 48,
["posY"] = 30,
["posX"] = 294,
},
},
["currentLayout"] = "Blizz Modern",
["racialCategories"] = {
["Draenei"] = false,
["Dracthyr"] = false,
["Worgen"] = false,
["ZandalariTroll"] = false,
["HighmountainTauren"] = false,
["Orc"] = false,
["Vulpera"] = false,
["BloodElf"] = false,
["Troll"] = false,
["Tauren"] = false,
["Nightborne"] = false,
["MagharOrc"] = false,
["KulTiran"] = false,
["Mechagnome"] = false,
["LightforgedDraenei"] = false,
["Goblin"] = false,
},
["statusText"] = {
["usePercentage"] = true,
},
["drCategories"] = {
["Incapacitate"] = false,
["Stun"] = false,
["Silence"] = false,
["Root"] = false,
["Disorient"] = false,
},
},
["Default"] = {
["layoutSettings"] = {
["BlizzArena"] = {
["scale"] = 1.8,
["posY"] = 7.8,
["posX"] = 214,
},
},
["statusText"] = {
["usePercentage"] = true,
},
["currentLayout"] = "BlizzTarget",
["drCategories"] = {
["Incapacitate"] = false,
["Root"] = false,
["Disorient"] = false,
["Stun"] = false,
["Silence"] = false,
},
},
["df-profile"] = {
["layoutSettings"] = {
["BlizzArena"] = {
["dr"] = {
["size"] = 19,
},
["posY"] = -27.4,
["scale"] = 1.6,
["trinket"] = {
["posY"] = 0,
},
["posX"] = 231.9,
["specIcon"] = {
["posY"] = -13,
["posX"] = 48,
},
},
["Xaryu"] = {
["posY"] = 30,
["castBar"] = {
["scale"] = 1.5,
["posX"] = -61,
},
["posX"] = 294,
["spacing"] = 48,
},
["Blizz Modern"] = {
["dr"] = {
["posY"] = 30,
["posX"] = -200,
["size"] = 36,
},
["posY"] = -11.7,
["scale"] = 0.9,
["specIcon"] = {
["scale"] = 1.2,
["posY"] = -19,
["posX"] = 77,
},
["castBar"] = {
["scale"] = 1.8,
["posX"] = -142,
["posY"] = 1,
["width"] = 84,
},
["classIconFontSize"] = 19,
["posX"] = 405.2,
["trinket"] = {
["scale"] = 1.4,
["posY"] = -2,
["posX"] = -84,
},
["racial"] = {
["scale"] = 1.4,
["posY"] = -2,
["posX"] = -113,
},
},
},
["racialCategories"] = {
["Dracthyr"] = false,
["HighmountainTauren"] = false,
["Orc"] = false,
["Troll"] = false,
["Earthen"] = false,
["Mechagnome"] = false,
["Vulpera"] = false,
["ZandalariTroll"] = false,
["Worgen"] = false,
["BloodElf"] = false,
["Nightborne"] = false,
["MagharOrc"] = false,
["LightforgedDraenei"] = false,
["Goblin"] = false,
},
["currentLayout"] = "Blizz Modern",
["statusText"] = {
["usePercentage"] = true,
},
["drCategories"] = {
["Knock"] = false,
["Root"] = false,
},
["drDynamicIcons"] = true,
},
["minimal"] = {
["layoutSettings"] = {
["BlizzArena"] = {
["dr"] = {
["size"] = 19,
},
["posY"] = -27.4,
["posX"] = 231.9,
["scale"] = 1.6,
["trinket"] = {
["posY"] = 0,
},
["specIcon"] = {
["posY"] = -13,
["posX"] = 48,
},
},
["Xaryu"] = {
["castBar"] = {
["scale"] = 1.5,
["posX"] = -61,
},
["spacing"] = 48,
["posY"] = 30,
["posX"] = 294,
},
["Blizz Modern"] = {
["dr"] = {
["size"] = 36,
["posY"] = 30,
["posX"] = -200,
},
["posY"] = -11.7,
["scale"] = 0.9,
["specIcon"] = {
["scale"] = 1.2,
["posY"] = -19,
["posX"] = 77,
},
["castBar"] = {
["scale"] = 1.8,
["posX"] = -142,
["posY"] = 1,
["width"] = 84,
},
["classIconFontSize"] = 19,
["posX"] = 405.2,
["trinket"] = {
["scale"] = 1.4,
["posY"] = -2,
["posX"] = -84,
},
["racial"] = {
["scale"] = 1.4,
["posY"] = -2,
["posX"] = -113,
},
},
},
["currentLayout"] = "Blizz Modern",
["racialCategories"] = {
["Dracthyr"] = false,
["MagharOrc"] = false,
["Earthen"] = false,
["Orc"] = false,
["Goblin"] = false,
["LightforgedDraenei"] = false,
["Troll"] = false,
["BloodElf"] = false,
["Nightborne"] = false,
["Worgen"] = false,
["HighmountainTauren"] = false,
["Mechagnome"] = false,
["Vulpera"] = false,
["ZandalariTroll"] = false,
},
["statusText"] = {
["usePercentage"] = true,
},
["drCategories"] = {
["Root"] = false,
["Knock"] = false,
},
["drDynamicIcons"] = true,
},
["left-side"] = {
["layoutSettings"] = {
["BlizzArena"] = {
["dr"] = {
["size"] = 19,
},
["posY"] = 129.4,
["posX"] = -94.6,
["scale"] = 1.6,
["specIcon"] = {
["posY"] = -13,
["posX"] = 48,
},
["trinket"] = {
["scale"] = 0.9,
["posY"] = -22,
["posX"] = 13,
},
["racial"] = {
["scale"] = 0.9,
["posY"] = -22,
["posX"] = -11,
},
},
["Xaryu"] = {
["castBar"] = {
["scale"] = 1.5,
["posX"] = -61,
},
["posX"] = 294,
["posY"] = 30,
["spacing"] = 48,
},
},
["statusText"] = {
["usePercentage"] = true,
},
["drCategories"] = {
["Incapacitate"] = false,
["Root"] = false,
["Silence"] = false,
["Stun"] = false,
["Disorient"] = false,
},
},
["MONK"] = {
["layoutSettings"] = {
["BlizzArena"] = {
["dr"] = {
["size"] = 19,
},
["posY"] = -27.4,
["posX"] = 231.9,
["scale"] = 1.6,
["trinket"] = {
["posY"] = 0,
},
["specIcon"] = {
["posY"] = -13,
["posX"] = 48,
},
},
["Xaryu"] = {
["castBar"] = {
["scale"] = 1.5,
["posX"] = -61,
},
["posX"] = 294,
["posY"] = 30,
["spacing"] = 48,
},
["Blizz Modern"] = {
["dr"] = {
["size"] = 36,
["posY"] = 30,
["posX"] = -200,
},
["posY"] = -11.7,
["scale"] = 0.9,
["specIcon"] = {
["scale"] = 1.2,
["posY"] = -19,
["posX"] = 77,
},
["castBar"] = {
["scale"] = 1.8,
["width"] = 84,
["posY"] = 1,
["posX"] = -142,
},
["classIconFontSize"] = 19,
["racial"] = {
["scale"] = 1.4,
["posY"] = -2,
["posX"] = -113,
},
["trinket"] = {
["scale"] = 1.4,
["posY"] = -2,
["posX"] = -84,
},
["posX"] = 405.2,
},
},
["currentLayout"] = "Blizz Modern",
["racialCategories"] = {
["Dracthyr"] = false,
["MagharOrc"] = false,
["Earthen"] = false,
["Orc"] = false,
["Goblin"] = false,
["Vulpera"] = false,
["Troll"] = false,
["BloodElf"] = false,
["Nightborne"] = false,
["Worgen"] = false,
["HighmountainTauren"] = false,
["Mechagnome"] = false,
["LightforgedDraenei"] = false,
["ZandalariTroll"] = false,
},
["statusText"] = {
["usePercentage"] = true,
},
["drDynamicIcons"] = true,
["drCategories"] = {
["Root"] = false,
["Knock"] = false,
},
},
["mysticall-main-tww"] = {
["layoutSettings"] = {
["BlizzArena"] = {
["dr"] = {
["size"] = 19,
},
["posY"] = -27.4,
["scale"] = 1.6,
["specIcon"] = {
["posY"] = -13,
["posX"] = 48,
},
["posX"] = 231.9,
["trinket"] = {
["posY"] = 0,
},
},
["Xaryu"] = {
["spacing"] = 48,
["castBar"] = {
["scale"] = 1.5,
["posX"] = -61,
},
["posX"] = 294,
["posY"] = 30,
},
["Blizz Modern"] = {
["dr"] = {
["posY"] = 30,
["posX"] = -200,
["size"] = 36,
},
["posY"] = -11.7,
["scale"] = 0.9,
["specIcon"] = {
["scale"] = 1.2,
["posY"] = -19,
["posX"] = 77,
},
["castBar"] = {
["scale"] = 1.8,
["posX"] = -142,
["posY"] = 1,
["width"] = 84,
},
["classIconFontSize"] = 19,
["posX"] = 405.2,
["trinket"] = {
["scale"] = 1.4,
["posY"] = -2,
["posX"] = -84,
},
["racial"] = {
["scale"] = 1.4,
["posY"] = -2,
["posX"] = -113,
},
},
},
["racialCategories"] = {
["Dracthyr"] = false,
["HighmountainTauren"] = false,
["Orc"] = false,
["Vulpera"] = false,
["Mechagnome"] = false,
["ZandalariTroll"] = false,
["BloodElf"] = false,
["Worgen"] = false,
["Earthen"] = false,
["LightforgedDraenei"] = false,
["Nightborne"] = false,
["MagharOrc"] = false,
["Troll"] = false,
["Goblin"] = false,
},
["currentLayout"] = "Blizz Modern",
["drDynamicIcons"] = true,
["drCategories"] = {
["Knock"] = false,
["Root"] = false,
},
["statusText"] = {
["usePercentage"] = true,
},
},
},
}
