
sArena_ReloadedDB = {
["profileKeys"] = {
["Cocoonjkdead - Aerie Peak"] = "Default(OLD-Imported)",
["Justinjames - Sentinels"] = "Default(OLD-Imported)",
["Mstcll - Borean Tundra"] = "Default(OLD-Imported)",
["Mstcll - Garrosh"] = "Default(OLD-Imported)",
["Onlyplaypala - Sargeras"] = "Default(OLD-Imported)",
["Onlyplaymage - Sargeras"] = "Default(OLD-Imported)",
["Lotusflower - Dalvengyr"] = "Default(OLD-Imported)",
["Réðçräñé - Sargeras"] = "mysticall-main-tww(OLD-Imported)",
["Mstcll - Sargeras"] = "Default(OLD-Imported)",
["Magycall - Emerald Dream"] = "mysticall-main-tww(OLD-Imported)",
["Lotusflowers - Sargeras"] = "Default(OLD-Imported)",
["Vivifying - Sentinels"] = "Default(OLD-Imported)",
["Mysticallx - Tichondrius"] = "Default(OLD-Imported)",
["Flowerlotus - Sentinels"] = "Default(OLD-Imported)",
["Mw - Tichondrius"] = "mysticall-main-tww(OLD-Imported)",
["Hordebanker - Sargeras"] = "Default(OLD-Imported)",
["Mystweaver - Area 52"] = "Default(OLD-Imported)",
["Vezimmarr - Aerie Peak"] = "Default(OLD-Imported)",
["Onlyplaydh - Sargeras"] = "mysticall-main-tww(OLD-Imported)",
["Onlyplaymw - Durotan"] = "Default(OLD-Imported)",
["Trialfornowa - Cenarius"] = "Default(OLD-Imported)",
["Yungmyst - Sentinels"] = "Default(OLD-Imported)",
["Gréëñðrägøñ - Sargeras"] = "Default(OLD-Imported)",
["Mysticbankk - Area 52"] = "Default(OLD-Imported)",
["Mysticall - Moon Guard"] = "Default(OLD-Imported)",
["Soullkeeper - Tichondrius"] = "mysticall-main-tww(OLD-Imported)",
["Jje - Vek'nilash"] = "Default(OLD-Imported)",
["Mysticallxd - Sargeras"] = "Default(OLD-Imported)",
["Curthalar - Bladefist"] = "Default",
["Vivifying - Area 52"] = "Default(OLD-Imported)",
["Mwreroll - Sentinels"] = "Default(OLD-Imported)",
["Zft - Sentinels"] = "Default(OLD-Imported)",
["Onlyplaymonk - Sargeras"] = "Default(OLD-Imported)",
["Mysticallud - Arena Champions - US"] = "mysticall-main-tww(OLD-Imported)",
["Yungmyst - Sargeras"] = "Default(OLD-Imported)",
["Cocoonjkdead - Bleeding Hollow"] = "Default(OLD-Imported)",
["Andrista - Bloodhoof"] = "Default(OLD-Imported)",
["Coocoocachu - Sargeras"] = "Default(OLD-Imported)",
["Rsk - Shandris"] = "mysticall-main-tww(OLD-Imported)",
["Gréëñðrägoñ - Sargeras"] = "mysticall-main-tww(OLD-Imported)",
["Zft - Area 52"] = "Default(OLD-Imported)",
["Justinjames - Sargeras"] = "Default(OLD-Imported)",
["Mstcll - Blackhand"] = "mysticall-main-tww(OLD-Imported)",
["Ashdfh - Mythic Dungeon Heroes - US"] = "Default(OLD-Imported)",
["Wymoralt - Proudmoore"] = "Default(OLD-Imported)",
["Tealcrayon - Anetheron"] = "Default(OLD-Imported)",
["Mysticbankk - Sargeras"] = "Default(OLD-Imported)",
["Soullstëaler - Sentinels"] = "Default(OLD-Imported)",
["Mysticbankk - Garrosh"] = "Default(OLD-Imported)",
["Mysticbankk - Sentinels"] = "Default(OLD-Imported)",
["Representing - Area 52"] = "Default(OLD-Imported)",
["Iamdeadinsid - Sentinels"] = "Default(OLD-Imported)",
["Sevenseconds - Area 52"] = "Default(OLD-Imported)",
["Green - Eitrigg"] = "mysticall-main-tww(OLD-Imported)",
["Mstcll - Aerie Peak"] = "Default(OLD-Imported)",
["Curtimer - Emerald Dream"] = "Default(OLD-Imported)",
["Representing - Sargeras"] = "mysticall-main-tww(OLD-Imported)",
["Elamatrenn - Emerald Dream"] = "Default(OLD-Imported)",
["Hystoricall - Tichondrius"] = "Default(OLD-Imported)",
["Mysticbankk - Tichondrius"] = "Default(OLD-Imported)",
["Thunderbadx - Sargeras"] = "mysticall-main-tww(OLD-Imported)",
["Mstcll - Sentinels"] = "Default(OLD-Imported)",
["Onlyplaymonk - Area 52"] = "Default(OLD-Imported)",
["Mw - Turalyon"] = "Default(OLD-Imported)",
["Craaruun - Eitrigg"] = "Default(OLD-Imported)",
["Sadfeesaddsf - Nemesis"] = "Default(OLD-Imported)",
["Yungmyst - Area 52"] = "Default(OLD-Imported)",
["Mstcll - Blackwater Raiders"] = "Default(OLD-Imported)",
["Thunderbad - Sentinels"] = "mysticall-main-tww(OLD-Imported)",
["Stylle - Sentinels"] = "Default(OLD-Imported)",
["Mysticbollt - Garrosh"] = "Default(OLD-Imported)",
["Gracefulness - Sargeras"] = "mysticall-main-tww(OLD-Imported)",
["Mstcll - Area 52"] = "Default(OLD-Imported)",
["Mysticbollt - Area 52"] = "Default(OLD-Imported)",
["Lifedestroys - Tichondrius"] = "mysticall-main-tww(OLD-Imported)",
["Mw - Sargeras"] = "Default(OLD-Imported)",
["Onlyplaydru - Sargeras"] = "Default(OLD-Imported)",
["Hydraxises - Lightning's Blade"] = "Default(OLD-Imported)",
["Mysticallx - Sargeras"] = "mysticall-midnight",
["Mstcll - Echo Isles"] = "Default(OLD-Imported)",
["Hydraxicle - Lightning's Blade"] = "Default(OLD-Imported)",
["Mediumvibes - Sentinels"] = "Default(OLD-Imported)",
["Onlyplaysub - Sargeras"] = "Default(OLD-Imported)",
["Nerfmw - Sargeras"] = "mysticall-main-tww(OLD-Imported)",
["Baotu - Sargeras"] = "mysticall-main-tww(OLD-Imported)",
["Chithion - Zul'jin"] = "Default(OLD-Imported)",
["Healjkoom - Sargeras"] = "Default",
["Ggs - Detheroc"] = "mysticall-main-tww(OLD-Imported)",
["Misstickle - Sargeras"] = "Default(OLD-Imported)",
["Nightbllade - Area 52"] = "Default(OLD-Imported)",
["Hystoricall - Sentinels"] = "Default(OLD-Imported)",
["Enveloping - Area 52"] = "Default(OLD-Imported)",
["Onlyplayfury - Sargeras"] = "Default(OLD-Imported)",
},
["profiles"] = {
["mysticall-main-tww(OLD-Imported)"] = {
["layoutSettings"] = {
["BlizzArena"] = {
["dr"] = {
["blackDRBorder"] = false,
["drBorderGlowOff"] = false,
["drCategorySizeOffsets"] = {
},
["thickPixelBorder"] = false,
["showDRText"] = false,
["brightDRBorder"] = true,
["thinPixelBorder"] = false,
["size"] = 18,
},
["posY"] = -16.3,
["scale"] = 1.6,
["specIcon"] = {
["posY"] = -13,
["posX"] = 48,
},
["replaceClassIcon"] = false,
["castBar"] = {
["useModernCastbars"] = false,
["posX"] = -121,
},
["posX"] = 222.7,
["textures"] = {
["generalStatusBarTexture"] = "Blizzard",
},
["trinket"] = {
["posY"] = 0,
},
},
["BlizzTarget"] = {
["posY"] = 100,
["posX"] = 300,
},
["Blizz Modern"] = {
["dr"] = {
["size"] = 36,
["posY"] = 30,
["posX"] = -200,
},
["posY"] = -11.7,
["scale"] = 0.9,
["specIcon"] = {
["scale"] = 1.2,
["posY"] = -19,
["posX"] = 77,
},
["castBar"] = {
["scale"] = 1.8,
["width"] = 84,
["posY"] = 1,
["posX"] = -142,
},
["classIconFontSize"] = 19,
["racial"] = {
["scale"] = 1.4,
["posY"] = -2,
["posX"] = -113,
},
["trinket"] = {
["scale"] = 1.4,
["posY"] = -2,
["posX"] = -84,
},
["posX"] = 405.2,
},
["BlizzTourney"] = {
["dr"] = {
["posY"] = 13,
["size"] = 22,
},
["posY"] = 100,
["posX"] = 300,
["scale"] = 1.2,
["castBar"] = {
["scale"] = 1,
["posY"] = -14,
["posX"] = -110,
},
},
["Xaryu"] = {
["castBar"] = {
["scale"] = 1.5,
["posX"] = -61,
},
["posY"] = 30,
["posX"] = 294,
["scale"] = 1,
["spacing"] = 48,
},
},
["classColorNames"] = false,
["replaceHealerIcon"] = false,
["classColorFrameTexture"] = true,
["disableDRSwipe"] = true,
["currentLayout"] = "BlizzArena",
["colorTrinket"] = false,
["darkModeValue"] = 0.21,
["disableTrinketRacialSwipe"] = false,
["drDynamicIcons"] = true,
["drCategories"] = {
["Root"] = false,
},
["enableMasque"] = false,
["statusText"] = {
["alwaysShow"] = false,
["usePercentage"] = true,
},
["showArenaNumber"] = true,
["racialCategories"] = {
["Dracthyr"] = false,
["Worgen"] = false,
["Earthen"] = false,
["Orc"] = false,
["ZandalariTroll"] = false,
["LightforgedDraenei"] = false,
["Troll"] = false,
["BloodElf"] = false,
["Nightborne"] = false,
["MagharOrc"] = false,
["HighmountainTauren"] = false,
["Mechagnome"] = false,
["Vulpera"] = false,
["Goblin"] = false,
},
["darkMode"] = true,
["disableSwipeEdge"] = false,
["showNames"] = false,
["hideClassIcon"] = false,
["drResetTimeDEL"] = true,
["drResetTime"] = 18.5,
["reverseBarsFill"] = false,
["classColorFrameTextureHealerGreen"] = false,
["disableAurasOnClassIcon"] = false,
["colorMysteryGray"] = false,
["disableClassIconSwipe"] = false,
["shadowSightTimer"] = false,
},
["Default"] = {
["drResetTimeDEL"] = true,
["drResetTime"] = 18.5,
},
["mysticall-midnight"] = {
["layoutSettings"] = {
["BlizzArena"] = {
["dr"] = {
["blackDRBorder"] = false,
["drBorderGlowOff"] = false,
["size"] = 18,
["thickPixelBorder"] = false,
["showDRText"] = false,
["brightDRBorder"] = true,
["thinPixelBorder"] = false,
["drCategorySizeOffsets"] = {
},
},
["racial"] = {
["scale"] = 0.7,
["posY"] = 0,
["posX"] = -120,
},
["scale"] = 1.6,
["specIcon"] = {
["posY"] = -13,
["posX"] = 48,
},
["replaceClassIcon"] = false,
["castBar"] = {
["posX"] = -136,
["useModernCastbars"] = false,
},
["posX"] = 221.1,
["trinket"] = {
["posY"] = 0,
},
["posY"] = -3.3,
["textures"] = {
["generalStatusBarTexture"] = "Blizzard",
},
},
["BlizzTarget"] = {
["posY"] = 100,
["posX"] = 300,
},
["Blizz Modern"] = {
["dr"] = {
["posX"] = -200,
["posY"] = 30,
["size"] = 36,
},
["racial"] = {
["scale"] = 1.4,
["posY"] = -2,
["posX"] = -113,
},
["scale"] = 0.9,
["specIcon"] = {
["scale"] = 1.2,
["posY"] = -19,
["posX"] = 77,
},
["castBar"] = {
["scale"] = 1.8,
["posX"] = -142,
["posY"] = 1,
["width"] = 84,
},
["classIconFontSize"] = 19,
["posX"] = 405.2,
["trinket"] = {
["scale"] = 1.4,
["posY"] = -2,
["posX"] = -84,
},
["posY"] = -11.7,
},
["BlizzTourney"] = {
["dr"] = {
["posY"] = 13,
["size"] = 22,
},
["posY"] = 100,
["posX"] = 300,
["scale"] = 1.2,
["castBar"] = {
["scale"] = 1,
["posY"] = -14,
["posX"] = -110,
},
},
["Xaryu"] = {
["castBar"] = {
["scale"] = 1.5,
["posX"] = -61,
},
["posY"] = 30,
["spacing"] = 48,
["scale"] = 1,
["posX"] = 294,
},
},
["classColorNames"] = false,
["replaceHealerIcon"] = false,
["classColorFrameTexture"] = true,
["shadowSightTimer"] = false,
["currentLayout"] = "BlizzArena",
["colorTrinket"] = false,
["darkModeValue"] = 0.21,
["disableTrinketRacialSwipe"] = false,
["drDynamicIcons"] = true,
["disableClassIconSwipe"] = false,
["enableMasque"] = false,
["reverseBarsFill"] = false,
["showArenaNumber"] = true,
["racialCategories"] = {
["Dracthyr"] = false,
["MagharOrc"] = false,
["Earthen"] = false,
["Orc"] = false,
["Goblin"] = false,
["Vulpera"] = false,
["Troll"] = false,
["BloodElf"] = false,
["Nightborne"] = false,
["Worgen"] = false,
["HighmountainTauren"] = false,
["Mechagnome"] = false,
["LightforgedDraenei"] = false,
["ZandalariTroll"] = false,
},
["darkMode"] = true,
["disableSwipeEdge"] = false,
["showNames"] = false,
["statusText"] = {
["alwaysShow"] = false,
["usePercentage"] = true,
},
["drResetTimeDEL"] = true,
["drResetTime"] = 18.5,
["hideClassIcon"] = false,
["classColorFrameTextureHealerGreen"] = false,
["disableAurasOnClassIcon"] = false,
["colorMysteryGray"] = false,
["drCategories"] = {
["Root"] = false,
},
["disableDRSwipe"] = true,
},
["Default(OLD-Imported)"] = {
["layoutSettings"] = {
["BlizzArena"] = {
["scale"] = 1.8,
["posY"] = 7.8,
["posX"] = 214,
},
["BlizzTarget"] = {
["posY"] = 30,
["posX"] = 365.8,
},
},
["statusText"] = {
["usePercentage"] = true,
},
["currentLayout"] = "BlizzTarget",
["drCategories"] = {
["Incapacitate"] = false,
["Silence"] = false,
["Stun"] = false,
["Root"] = false,
["Disorient"] = false,
},
},
["Mysticallud - Arena Champions - US"] = {
},
},
}
