
SimpleCombatLoggerDB = {
["profileKeys"] = {
["Mysticallud - Arena Champions - US"] = "Default",
["Rsk - Shandris"] = "Default",
["Fanarassa - Sentinels"] = "Default",
["Mstcll - Sargeras"] = "Default",
["Onlyplaydh - Sargeras"] = "Default",
["Gréëñðrägoñ - Sargeras"] = "Default",
["Representing - Sargeras"] = "Default",
["Mwreroll - Sargeras"] = "Default",
["Gracefulness - Sargeras"] = "Default",
["Alunadris - Sentinels"] = "Default",
["Mysticbollt - Area 52"] = "Default",
["Mstcll - Blackhand"] = "Default",
["Badplat - Sargeras"] = "Default",
["Réðçräñé - Sargeras"] = "Default",
["Jje - Vek'nilash"] = "Default",
["Mysticallx - Sargeras"] = "Default",
["Curthalar - Bladefist"] = "Default",
["Thunderbad - Sentinels"] = "Default",
["Magycall - Emerald Dream"] = "Default",
["Azshauleand - Sargeras"] = "Default",
["Soullkeeper - Tichondrius"] = "Default",
["Green - Eitrigg"] = "Default",
["Healjkoom - Sargeras"] = "Default",
["Ruchi - Sentinels"] = "Default",
["Ggs - Detheroc"] = "Default",
["Mw - Tichondrius"] = "Default",
["Mediumvibes - Sentinels"] = "Default",
["Nerfmw - Sargeras"] = "Default",
["Sydarelora - Draenor"] = "Default",
["Thunderbadx - Sargeras"] = "Default",
},
["profiles"] = {
["Default"] = {
},
},
}
