
TrufiGCDGlSave = {
["lastUsedProfileId"] = "79edcb5d-7125-4475-979b-36d111d16d92",
["version"] = 1,
["profiles"] = {
["6e4bb5af-511f-4948-a2f4-7c06690a12ef"] = {
["TooltipEnable"] = true,
["TooltipStopMove"] = true,
["TrGCDQueueFr"] = {
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
},
["TooltipSpellID"] = false,
["EnableIn"] = {
["Combat only"] = false,
["Raid"] = true,
["World"] = true,
["Enable"] = true,
["Arena"] = true,
["Bg"] = true,
["PvE"] = true,
},
["ModScroll"] = true,
["name"] = "Thunderbad - Sentinels",
["TrGCDBL"] = {
6603,
75,
7384,
},
["iconClickAddsSpellToBlocklist"] = false,
["id"] = "6e4bb5af-511f-4948-a2f4-7c06690a12ef",
},
["38d9ff62-a677-4f2b-b891-59e36b8f292d"] = {
["TooltipEnable"] = true,
["TooltipStopMove"] = true,
["TrGCDQueueFr"] = {
{
["y"] = 119.0027084350586,
["x"] = 343.0005187988281,
["point"] = "BOTTOM",
["enable"] = true,
["width"] = 4,
["size"] = 51,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
},
["TooltipSpellID"] = false,
["EnableIn"] = {
["Combat only"] = false,
["Raid"] = true,
["World"] = true,
["Enable"] = true,
["Arena"] = true,
["Bg"] = true,
["PvE"] = true,
},
["ModScroll"] = true,
["name"] = "Kickthesun - Sargeras",
["TrGCDBL"] = {
6603,
75,
7384,
},
["iconClickAddsSpellToBlocklist"] = false,
["id"] = "38d9ff62-a677-4f2b-b891-59e36b8f292d",
},
["f70cf757-3e79-47d0-a0db-e423967c5a0e"] = {
["TooltipEnable"] = true,
["TooltipStopMove"] = true,
["TrGCDQueueFr"] = {
{
["y"] = 129.9998016357422,
["x"] = 417.0010681152344,
["point"] = "BOTTOM",
["enable"] = true,
["width"] = 4,
["size"] = 54,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
},
["TooltipSpellID"] = false,
["EnableIn"] = {
["Combat only"] = false,
["Raid"] = true,
["World"] = true,
["Enable"] = true,
["Arena"] = true,
["Bg"] = true,
["PvE"] = true,
},
["ModScroll"] = true,
["name"] = "Réðçräñé - Sargeras",
["TrGCDBL"] = {
6603,
75,
7384,
},
["iconClickAddsSpellToBlocklist"] = false,
["id"] = "f70cf757-3e79-47d0-a0db-e423967c5a0e",
},
["5ac15ef4-fbe7-4333-9a61-fc0ccb4ff644"] = {
["TooltipEnable"] = true,
["TooltipStopMove"] = true,
["TrGCDQueueFr"] = {
{
["y"] = 120.0027160644531,
["x"] = 415.0006713867188,
["point"] = "BOTTOM",
["enable"] = true,
["width"] = 4,
["size"] = 51,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = -104.9999313354492,
["x"] = -332.0003662109375,
["point"] = "TOP",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
},
["TooltipSpellID"] = false,
["EnableIn"] = {
["Combat only"] = false,
["Raid"] = true,
["World"] = true,
["Enable"] = true,
["Arena"] = true,
["Bg"] = true,
["PvE"] = true,
},
["ModScroll"] = true,
["name"] = "Badplat - Sargeras",
["TrGCDBL"] = {
6603,
75,
7384,
},
["iconClickAddsSpellToBlocklist"] = false,
["id"] = "5ac15ef4-fbe7-4333-9a61-fc0ccb4ff644",
},
["2fc7a924-c974-4d1e-8234-466d7a91affb"] = {
["TooltipEnable"] = true,
["TooltipStopMove"] = true,
["TrGCDQueueFr"] = {
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = true,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
},
["TooltipSpellID"] = false,
["EnableIn"] = {
["Combat only"] = false,
["Raid"] = true,
["World"] = true,
["Enable"] = true,
["Arena"] = true,
["Bg"] = true,
["PvE"] = true,
},
["ModScroll"] = true,
["name"] = "Flowerlotus - Sentinels",
["TrGCDBL"] = {
6603,
75,
7384,
},
["iconClickAddsSpellToBlocklist"] = false,
["id"] = "2fc7a924-c974-4d1e-8234-466d7a91affb",
},
["79edcb5d-7125-4475-979b-36d111d16d92"] = {
["TooltipEnable"] = true,
["TooltipStopMove"] = true,
["TrGCDQueueFr"] = {
{
["y"] = 149.1691741943359,
["x"] = 5.834763050079346,
["point"] = "BOTTOM",
["enable"] = true,
["width"] = 7,
["size"] = 36,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = -104.9999313354492,
["x"] = -332.0003662109375,
["point"] = "TOP",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
},
["TooltipSpellID"] = false,
["EnableIn"] = {
["Combat only"] = false,
["Raid"] = true,
["World"] = true,
["Enable"] = true,
["Arena"] = true,
["Bg"] = true,
["PvE"] = true,
},
["ModScroll"] = true,
["name"] = "Mysticallx - Sargeras",
["TrGCDBL"] = {
6603,
75,
7384,
162530,
229837,
91743,
176890,
185712,
170869,
179950,
440836,
431490,
444714,
366340,
368256,
442385,
223143,
156098,
464257,
453864,
412168,
131474,
143394,
8690,
372608,
},
["iconClickAddsSpellToBlocklist"] = true,
["id"] = "79edcb5d-7125-4475-979b-36d111d16d92",
},
["d98e3289-9b1f-43ca-8e87-93e9358fb2df"] = {
["TooltipEnable"] = true,
["TooltipStopMove"] = true,
["TrGCDQueueFr"] = {
{
["y"] = 261.9999694824219,
["x"] = 197.9997100830078,
["point"] = "BOTTOM",
["enable"] = true,
["width"] = 3,
["size"] = 37,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
{
["y"] = 0,
["x"] = 0,
["point"] = "CENTER",
["enable"] = false,
["width"] = 3,
["size"] = 30,
["fade"] = "Left",
},
},
["TooltipSpellID"] = false,
["EnableIn"] = {
["Combat only"] = false,
["Raid"] = true,
["World"] = true,
["Enable"] = true,
["Arena"] = true,
["Bg"] = true,
["PvE"] = true,
},
["ModScroll"] = true,
["name"] = "Mw - Tichondrius",
["TrGCDBL"] = {
6603,
75,
7384,
},
["iconClickAddsSpellToBlocklist"] = false,
["id"] = "d98e3289-9b1f-43ca-8e87-93e9358fb2df",
},
},
}
